##### How it is different from numpy?
It is difficult to work with data having heterogenous values using Numpy.<br>
<b>Pandas</b> can work with data having numbers and string together.

In [2]:
import pandas as pd
import numpy as np

In [3]:
#Reading dataset in pandas
dataset = pd.read_csv('mckinsey.csv')

In [173]:
dataset

country  year  population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1699     Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298

[1704 rows x 6 columns]

Observation
<br>We can see that it has: 1704 rows and 6 columns

In [174]:
type(dataset)

pandas.core.frame.DataFrame

##### What is pandas dataframe?
It is a table-like repersentation of data in pandas (structured data).<br>Structured data --> as tabular data in a proper order.<br>Considered as counterpart of 2D-matrix in Numpy.

In [175]:
dataset['country'] #we can get all the values in the column country

0       Afghanistan
1       Afghanistan
2       Afghanistan
3       Afghanistan
4       Afghanistan
           ...     
1699       Zimbabwe
1700       Zimbabwe
1701       Zimbabwe
1702       Zimbabwe
1703       Zimbabwe
Name: country, Length: 1704, dtype: object

What is the data-type of this column?

In [176]:
type(dataset['country'])

pandas.core.series.Series

##### What is a pandas series?
A Series is a single column of a data.<br>Series in pandas is what a Vector is in Numpy.<br>Multiple Series stack together to form a dataframe.

In [177]:
#We can find data-type, name, total entries in each column.
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1704 entries, 0 to 1703
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   country     1704 non-null   object 
 1   year        1704 non-null   int64  
 2   population  1704 non-null   int64  
 3   continent   1704 non-null   object 
 4   life_exp    1704 non-null   float64
 5   gdp_cap     1704 non-null   float64
dtypes: float64(2), int64(2), object(2)
memory usage: 80.0+ KB


##### dataset.info() gives a list of columns with:
Name of the columns<br>
How many non-null values (blank cells) each column has.<br>
types of values in each column - int, float etc<br>
By default, it shows data-type as object for anything other that int or float.

In [178]:
#Display first five rows
# dataset.head()
dataset.head(10) #specify the number of rows you want to see.

country  year  population continent  life_exp     gdp_cap
0  Afghanistan  1952     8425333      Asia    28.801  779.445314
1  Afghanistan  1957     9240934      Asia    30.332  820.853030
2  Afghanistan  1962    10267083      Asia    31.997  853.100710
3  Afghanistan  1967    11537966      Asia    34.020  836.197138
4  Afghanistan  1972    13079460      Asia    36.088  739.981106
5  Afghanistan  1977    14880372      Asia    38.438  786.113360
6  Afghanistan  1982    12881816      Asia    39.854  978.011439
7  Afghanistan  1987    13867957      Asia    40.822  852.395945
8  Afghanistan  1992    16317921      Asia    41.674  649.341395
9  Afghanistan  1997    22227415      Asia    41.763  635.341351

In [179]:
#Display the last 5 rows 
dataset.tail()
# dataset.tail(10) #for last 10 rows

country  year  population continent  life_exp     gdp_cap
1699  Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700  Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701  Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702  Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703  Zimbabwe  2007    12311143    Africa    43.487  469.709298

In [180]:
dataset.shape #similar to Numpy, it gives No. of rows and columns --- Dimension

(1704, 6)

#### Lets Create a DataFrame from Scratch.
##### Approach 1: Row-oriented
<li>It takes 2 arguments</li>
A list of rows:<li>Each row is packed in a list [].</li><li>all rows are packed in an outside list [ [] ].</li>
<li>A list of columns names/labels.</li>


In [181]:
pd.DataFrame([['Afganistan',1992,123213,'Asia',24.343,779.3432],
              ['Uzbezkistan',1990,23342,'Asia',10.343,710.124],
              ['Afganistan',1992,34243,'Asia',89.343,910.2112],
              ['Afganistan',1991,234234,'Asia',30.343,133.121]],
             columns=['Country','Year','Population','Continent','life_exp','gdp_cap'])


Country  Year  Population Continent  life_exp   gdp_cap
0   Afganistan  1992      123213      Asia    24.343  779.3432
1  Uzbezkistan  1990       23342      Asia    10.343  710.1240
2   Afganistan  1992       34243      Asia    89.343  910.2112
3   Afganistan  1991      234234      Asia    30.343  133.1210

#### Approach 2: Column-oriented

In [182]:
#We pass the data as dictionary
pd.DataFrame({'Country':['Afganistan','India'],
              'year':[1920,1910],
              'Population':[123123,124435],
              'Continent':['Asia','Asia'],
              'Life_exp':[28.32,30.23],
              'gdp_cap':[412.214,124.234]})
#key is the column name
#Value is the list of values column-wise

Country  year  Population Continent  Life_exp  gdp_cap
0  Afganistan  1920      123123      Asia     28.32  412.214
1       India  1910      124435      Asia     30.23  124.234

In [183]:
#What if our dataset has 20 cols or 100 cols? We can't see their name in one go.
#How can we get the names of all these cols?
dataset.columns #using columns attribute of a dataframe


Index(['country', 'year', 'population', 'continent', 'life_exp', 'gdp_cap'], dtype='object')

In [184]:
dataset.keys()

Index(['country', 'year', 'population', 'continent', 'life_exp', 'gdp_cap'], dtype='object')

<li>Here, Index is a type of pandas class used to store the address of the series/dataframe</li>
<li>It is an immutable sequence used for indexing and alignment</li>

In [185]:
dataset[['country','life_exp']].head() # [ ['Country'] ] gives a dataframe 

country  life_exp
0  Afghanistan    28.801
1  Afghanistan    30.332
2  Afghanistan    31.997
3  Afghanistan    34.020
4  Afghanistan    36.088

In [186]:
dataset['country'] #['Country'] gives a series

0       Afghanistan
1       Afghanistan
2       Afghanistan
3       Afghanistan
4       Afghanistan
           ...     
1699       Zimbabwe
1700       Zimbabwe
1701       Zimbabwe
1702       Zimbabwe
1703       Zimbabwe
Name: country, Length: 1704, dtype: object

In [187]:
#How can we find unique values in a column?
dataset['country'].unique()

array(['Afghanistan', 'Albania', 'Algeria', 'Angola', 'Argentina',
       'Australia', 'Austria', 'Bahrain', 'Bangladesh', 'Belgium',
       'Benin', 'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil',
       'Bulgaria', 'Burkina Faso', 'Burundi', 'Cambodia', 'Cameroon',
       'Canada', 'Central African Republic', 'Chad', 'Chile', 'China',
       'Colombia', 'Comoros', 'Congo, Dem. Rep.', 'Congo, Rep.',
       'Costa Rica', "Cote d'Ivoire", 'Croatia', 'Cuba', 'Czech Republic',
       'Denmark', 'Djibouti', 'Dominican Republic', 'Ecuador', 'Egypt',
       'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Ethiopia',
       'Finland', 'France', 'Gabon', 'Gambia', 'Germany', 'Ghana',
       'Greece', 'Guatemala', 'Guinea', 'Guinea-Bissau', 'Haiti',
       'Honduras', 'Hong Kong, China', 'Hungary', 'Iceland', 'India',
       'Indonesia', 'Iran', 'Iraq', 'Ireland', 'Israel', 'Italy',
       'Jamaica', 'Japan', 'Jordan', 'Kenya', 'Korea, Dem. Rep.',
       'Korea, Rep.', 'Kuwait', 'Leba

In [188]:
#count of each country in the dataframe
dataset['country'].value_counts()

country
Afghanistan          12
Pakistan             12
New Zealand          12
Nicaragua            12
Niger                12
                     ..
Eritrea              12
Equatorial Guinea    12
El Salvador          12
Egypt                12
Zimbabwe             12
Name: count, Length: 142, dtype: int64

value_counts() shows the output in decreasing order of frequency

#### What we want to rename a column?
We can remane the column by:<br>
<li>passing the dictionary with old_name:new_name pair.</li>
<li>specifying axis = 1</li>

In [189]:
dataset.rename({'population':'Population','country':'Country'},axis=1)

Country  year  Population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1699     Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298

[1704 rows x 6 columns]

In [190]:
dataset.rename(columns={'country':'Country'},inplace=True)

In [191]:
dataset

Country  year  population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1699     Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298

[1704 rows x 6 columns]

In [192]:
dataset.population #not a convienent way of accessing the columns 
#if the column names are not string or contains a space(eg 2nd, Roll number)


0        8425333
1        9240934
2       10267083
3       11537966
4       13079460
          ...   
1699     9216418
1700    10704340
1701    11404948
1702    11926563
1703    12311143
Name: population, Length: 1704, dtype: int64

##### How we can delete columns in pandas dataframe

In [193]:
# dataset.drop('continent',axis=1)  #this will not delete the column from the actual dataset
dataset.drop(columns=['continent'])

Country  year  population  life_exp     gdp_cap
0     Afghanistan  1952     8425333    28.801  779.445314
1     Afghanistan  1957     9240934    30.332  820.853030
2     Afghanistan  1962    10267083    31.997  853.100710
3     Afghanistan  1967    11537966    34.020  836.197138
4     Afghanistan  1972    13079460    36.088  739.981106
...           ...   ...         ...       ...         ...
1699     Zimbabwe  1987     9216418    62.351  706.157306
1700     Zimbabwe  1992    10704340    60.377  693.420786
1701     Zimbabwe  1997    11404948    46.809  792.449960
1702     Zimbabwe  2002    11926563    39.989  672.038623
1703     Zimbabwe  2007    12311143    43.487  469.709298

[1704 rows x 5 columns]

Has the column permanently been deleted? No, We only got a view of dataframe with column continent dropped.<br>
How we can permanently drop the column?
<li>df = df.drop('continent',axis=1) i.e we can either re-assign it. </li>
<li>We can set parameter inplace=True</li>

In [194]:
dataset.drop('continent',axis=1,inplace=True) #it will permanently deleted the column

In [195]:
dataset

Country  year  population  life_exp     gdp_cap
0     Afghanistan  1952     8425333    28.801  779.445314
1     Afghanistan  1957     9240934    30.332  820.853030
2     Afghanistan  1962    10267083    31.997  853.100710
3     Afghanistan  1967    11537966    34.020  836.197138
4     Afghanistan  1972    13079460    36.088  739.981106
...           ...   ...         ...       ...         ...
1699     Zimbabwe  1987     9216418    62.351  706.157306
1700     Zimbabwe  1992    10704340    60.377  693.420786
1701     Zimbabwe  1997    11404948    46.809  792.449960
1702     Zimbabwe  2002    11926563    39.989  672.038623
1703     Zimbabwe  2007    12311143    43.487  469.709298

[1704 rows x 5 columns]

##### How we can create a column using values from exsisting columns?

In [196]:
dataset['year+7'] = dataset['year'] + 7
dataset.head()

Country  year  population  life_exp     gdp_cap  year+7
0  Afghanistan  1952     8425333    28.801  779.445314    1959
1  Afghanistan  1957     9240934    30.332  820.853030    1964
2  Afghanistan  1962    10267083    31.997  853.100710    1969
3  Afghanistan  1967    11537966    34.020  836.197138    1974
4  Afghanistan  1972    13079460    36.088  739.981106    1979

#### Working with Rows

In [197]:
dataset.index.values

array([   0,    1,    2, ..., 1701, 1702, 1703], dtype=int64)

In [6]:
dataset.index

RangeIndex(start=0, stop=1704, step=1)

In [198]:
#can we change row labels ---> lets start the indexing from 1 instead of 0.
dataset.index = list(range(1,dataset.shape[0]+1))

In [199]:
dataset

Country  year  population  life_exp     gdp_cap  year+7
1     Afghanistan  1952     8425333    28.801  779.445314    1959
2     Afghanistan  1957     9240934    30.332  820.853030    1964
3     Afghanistan  1962    10267083    31.997  853.100710    1969
4     Afghanistan  1967    11537966    34.020  836.197138    1974
5     Afghanistan  1972    13079460    36.088  739.981106    1979
...           ...   ...         ...       ...         ...     ...
1700     Zimbabwe  1987     9216418    62.351  706.157306    1994
1701     Zimbabwe  1992    10704340    60.377  693.420786    1999
1702     Zimbabwe  1997    11404948    46.809  792.449960    2004
1703     Zimbabwe  2002    11926563    39.989  672.038623    2009
1704     Zimbabwe  2007    12311143    43.487  469.709298    2014

[1704 rows x 6 columns]

row labels/indices ---> They can be called identifiers of a particular row.
<br>Specially known as explicit indices.


In [200]:
dataset.index[1] #implicit index 1 of row to give its explicit index.

2

In [201]:
sample = dataset.head()
sample

Country  year  population  life_exp     gdp_cap  year+7
1  Afghanistan  1952     8425333    28.801  779.445314    1959
2  Afghanistan  1957     9240934    30.332  820.853030    1964
3  Afghanistan  1962    10267083    31.997  853.100710    1969
4  Afghanistan  1967    11537966    34.020  836.197138    1974
5  Afghanistan  1972    13079460    36.088  739.981106    1979

In [202]:
#we use string as indices
sample.index = ["a","b","c","d","e"]
sample

Country  year  population  life_exp     gdp_cap  year+7
a  Afghanistan  1952     8425333    28.801  779.445314    1959
b  Afghanistan  1957     9240934    30.332  820.853030    1964
c  Afghanistan  1962    10267083    31.997  853.100710    1969
d  Afghanistan  1967    11537966    34.020  836.197138    1974
e  Afghanistan  1972    13079460    36.088  739.981106    1979

In [203]:
#accessing a subsets of row using slicing 
dataset['country'][5:15]

KeyError: 'country'

#### accessing rows in dataframe


In [ ]:
#loc ---> allows indexing and slicing that always reference the explicit index
dataset[0:3] #slicing however checked for implicit indices
# dataset[0] #raise error as in this dataset it starts from 1 and indexing in dataframe looks only for explicit indices.

country  year  population  life_exp     gdp_cap  year+7
1  Afghanistan  1952     8425333    28.801  779.445314    1959
2  Afghanistan  1957     9240934    30.332  820.853030    1964
3  Afghanistan  1962    10267083    31.997  853.100710    1969

In [ ]:
dataset.loc[1]

country       Afghanistan
year                 1952
population        8425333
life_exp           28.801
gdp_cap        779.445314
year+7               1959
Name: 1, dtype: object

In [ ]:
dataset.loc[1:10]

country  year  population  life_exp     gdp_cap  year+7
1   Afghanistan  1952     8425333    28.801  779.445314    1959
2   Afghanistan  1957     9240934    30.332  820.853030    1964
3   Afghanistan  1962    10267083    31.997  853.100710    1969
4   Afghanistan  1967    11537966    34.020  836.197138    1974
5   Afghanistan  1972    13079460    36.088  739.981106    1979
6   Afghanistan  1977    14880372    38.438  786.113360    1984
7   Afghanistan  1982    12881816    39.854  978.011439    1989
8   Afghanistan  1987    13867957    40.822  852.395945    1994
9   Afghanistan  1992    16317921    41.674  649.341395    1999
10  Afghanistan  1997    22227415    41.763  635.341351    2004

In [ ]:
#iloc ---> allows indexing and slicing that always reference the implicit python-style index
dataset.iloc[1]

country       Afghanistan
year                 1957
population        9240934
life_exp           30.332
gdp_cap         820.85303
year+7               1964
Name: 2, dtype: object

In [ ]:
#Now will iloc also consider the range inclusive 
#because iloc works with implicit Python-style indices
dataset.iloc[0:2]

country  year  population  life_exp     gdp_cap  year+7
1  Afghanistan  1952     8425333    28.801  779.445314    1959
2  Afghanistan  1957     9240934    30.332  820.853030    1964

In [ ]:
#Accessing multiple non-consecutive rows at a same time
dataset.iloc[[1,19,12]]

Country  year  population  life_exp      gdp_cap  year+7
2   Afghanistan  1957     9240934    30.332   820.853030    1964
20      Albania  1987     3075321    72.000  3738.932735    1994
13      Albania  1952     1282697    55.230  1601.056136    1959

In [ ]:
#incase of negative index 
# dataset.loc[-1] #it will raise keyerror because loc works with assigned labels.
dataset.iloc[-1] #iloc works with positional indices, [-1] here points to the row at last position in iloc

Country         Zimbabwe
year                2007
population      12311143
life_exp          43.487
gdp_cap       469.709298
year+7              2014
Name: 1704, dtype: object

In [ ]:
#Now---setting column name as index
temporary_df = dataset.set_index('year')
temporary_df

Country  population  life_exp     gdp_cap  year+7
year                                                       
1952  Afghanistan     8425333    28.801  779.445314    1959
1957  Afghanistan     9240934    30.332  820.853030    1964
1962  Afghanistan    10267083    31.997  853.100710    1969
1967  Afghanistan    11537966    34.020  836.197138    1974
1972  Afghanistan    13079460    36.088  739.981106    1979
...           ...         ...       ...         ...     ...
1987     Zimbabwe     9216418    62.351  706.157306    1994
1992     Zimbabwe    10704340    60.377  693.420786    1999
1997     Zimbabwe    11404948    46.809  792.449960    2004
2002     Zimbabwe    11926563    39.989  672.038623    2009
2007     Zimbabwe    12311143    43.487  469.709298    2014

[1704 rows x 5 columns]

In [ ]:
#if you would pass a year 1972 as index
temporary_df.loc[1972] #It gives all the value that has index 1972

Country  population  life_exp      gdp_cap  year+7
year                                                               
1972         Afghanistan    13079460    36.088   739.981106    1979
1972             Albania     2263554    67.690  3313.422188    1979
1972             Algeria    14760787    54.518  4182.663766    1979
1972              Angola     5894858    37.928  5473.288005    1979
1972           Argentina    24779799    67.065  9443.038526    1979
...                  ...         ...       ...          ...     ...
1972             Vietnam    44655014    50.254   699.501644    1979
1972  West Bank and Gaza     1089572    56.532  3133.409277    1979
1972         Yemen, Rep.     7407075    39.848  1265.047031    1979
1972              Zambia     4506497    50.107  1773.498265    1979
1972            Zimbabwe     5861135    55.635   799.362176    1979

[142 rows x 5 columns]

In [ ]:
#How to reset index?
dataset.reset_index()

index      Country  year  population  life_exp     gdp_cap  year+7
0         1  Afghanistan  1952     8425333    28.801  779.445314    1959
1         2  Afghanistan  1957     9240934    30.332  820.853030    1964
2         3  Afghanistan  1962    10267083    31.997  853.100710    1969
3         4  Afghanistan  1967    11537966    34.020  836.197138    1974
4         5  Afghanistan  1972    13079460    36.088  739.981106    1979
...     ...          ...   ...         ...       ...         ...     ...
1699   1700     Zimbabwe  1987     9216418    62.351  706.157306    1994
1700   1701     Zimbabwe  1992    10704340    60.377  693.420786    1999
1701   1702     Zimbabwe  1997    11404948    46.809  792.449960    2004
1702   1703     Zimbabwe  2002    11926563    39.989  672.038623    2009
1703   1704     Zimbabwe  2007    12311143    43.487  469.709298    2014

[1704 rows x 7 columns]

In [ ]:
#reset index without creating a new column of nameed index
dataset.reset_index(drop=True,inplace=True)

In [ ]:
dataset

Country  year  population  life_exp     gdp_cap  year+7
0     Afghanistan  1952     8425333    28.801  779.445314    1959
1     Afghanistan  1957     9240934    30.332  820.853030    1964
2     Afghanistan  1962    10267083    31.997  853.100710    1969
3     Afghanistan  1967    11537966    34.020  836.197138    1974
4     Afghanistan  1972    13079460    36.088  739.981106    1979
...           ...   ...         ...       ...         ...     ...
1699     Zimbabwe  1987     9216418    62.351  706.157306    1994
1700     Zimbabwe  1992    10704340    60.377  693.420786    1999
1701     Zimbabwe  1997    11404948    46.809  792.449960    2004
1702     Zimbabwe  2002    11926563    39.989  672.038623    2009
1703     Zimbabwe  2007    12311143    43.487  469.709298    2014

[1704 rows x 6 columns]

In [ ]:
#How we can add a row to out dataframe
""" 
    #In older version -> we can add a row using append() method.
    #It is obsolate in the higher version.
    append() 
        - it doesn't mutate the dataframe
        - it returns a new dataframe with the row appended.
        
    #using loc[] - we need to provide the position at which we will add the new row.
                 - Adding a row at a specific index position will replace the exixting row at the position.
    
"""
print(len(dataset.index))
dataset.loc[len(dataset.index)] = ['Ababua',3002,543,90.33,3452.043,3009]

1706


In [ ]:
#using iloc[] 
print(len(dataset.index))
dataset.iloc[len(dataset.index)] = ['Halua',3002,543,90.33,3452.043,3009] #iloc cannot enlarge its target object

1708


IndexError: iloc cannot enlarge its target object

In [ ]:
dataset.iloc[len(dataset.index)-3] = ['Halua',3002,543,90.33,3452.043,3009] #adding a row at a specific index postiton can possible - it will replace the existing row at that position

In [ ]:
dataset

Country  year  population  life_exp      gdp_cap  year+7
0     Afghanistan  1952     8425333    28.801   779.445314    1959
1     Afghanistan  1957     9240934    30.332   820.853030    1964
2     Afghanistan  1962    10267083    31.997   853.100710    1969
3     Afghanistan  1967    11537966    34.020   836.197138    1974
4     Afghanistan  1972    13079460    36.088   739.981106    1979
...           ...   ...         ...       ...          ...     ...
1703        India  1001       12313    34.330  9809.043000    1008
1704     Tulkalam  2001        6793    90.330  1077.043000    9001
1705        Halua  3002         543    90.330  3452.043000    3009
1706     Tulkalam  2001        6793    90.330  1077.043000    9001
1707        Halua  3002         543    90.330  3452.043000    3009

[1708 rows x 6 columns]

In [ ]:
#Now, what if I want to delete a row?
''' 
    Use df.drop() -> we specified axis =1 for columns
    we can modify this for rows:
        - We can use axis = 0
    - drop() method uses labels, NOT positional indices.
'''
df = dataset.drop(1703,axis=0)
df

Country  year  population  life_exp      gdp_cap  year+7
0     Afghanistan  1952     8425333    28.801   779.445314    1959
1     Afghanistan  1957     9240934    30.332   820.853030    1964
2     Afghanistan  1962    10267083    31.997   853.100710    1969
3     Afghanistan  1967    11537966    34.020   836.197138    1974
4     Afghanistan  1972    13079460    36.088   739.981106    1979
...           ...   ...         ...       ...          ...     ...
1702     Zimbabwe  2002    11926563    39.989   672.038623    2009
1704     Tulkalam  2001        6793    90.330  1077.043000    9001
1705        Halua  3002         543    90.330  3452.043000    3009
1706     Tulkalam  2001        6793    90.330  1077.043000    9001
1707        Halua  3002         543    90.330  3452.043000    3009

[1707 rows x 6 columns]

In [ ]:
#let's drop multiple rows
df.drop([1,3,5,1706],axis=0) #haahaa


Country  year  population  life_exp      gdp_cap  year+7
0     Afghanistan  1952     8425333    28.801   779.445314    1959
2     Afghanistan  1962    10267083    31.997   853.100710    1969
4     Afghanistan  1972    13079460    36.088   739.981106    1979
6     Afghanistan  1982    12881816    39.854   978.011439    1989
7     Afghanistan  1987    13867957    40.822   852.395945    1994
...           ...   ...         ...       ...          ...     ...
1701     Zimbabwe  1997    11404948    46.809   792.449960    2004
1702     Zimbabwe  2002    11926563    39.989   672.038623    2009
1704     Tulkalam  2001        6793    90.330  1077.043000    9001
1705        Halua  3002         543    90.330  3452.043000    3009
1707        Halua  3002         543    90.330  3452.043000    3009

[1703 rows x 6 columns]

In [ ]:
df.reset_index(drop=True,inplace=True)

<b>Dealing with duplicates row </b>

In [ ]:
dataset

Country  year  population  life_exp      gdp_cap  year+7
0     Afghanistan  1952     8425333    28.801   779.445314    1959
1     Afghanistan  1957     9240934    30.332   820.853030    1964
2     Afghanistan  1962    10267083    31.997   853.100710    1969
3     Afghanistan  1967    11537966    34.020   836.197138    1974
4     Afghanistan  1972    13079460    36.088   739.981106    1979
...           ...   ...         ...       ...          ...     ...
1703        India  1001       12313    34.330  9809.043000    1008
1704     Tulkalam  2001        6793    90.330  1077.043000    9001
1705        Halua  3002         543    90.330  3452.043000    3009
1706     Tulkalam  2001        6793    90.330  1077.043000    9001
1707        Halua  3002         543    90.330  3452.043000    3009

[1708 rows x 6 columns]

In [ ]:
dataset.loc[len(dataset.index)] = ['India',1001,12313,34.330, 9809.043000, 1008]

In [ ]:
#how we can check for duplicate rows?
''' 
    Use duplicated() method on the dataframe
'''
dataset.duplicated() #It output True if an entire row is identical to previous row

0       False
1       False
2       False
3       False
4       False
        ...  
1704    False
1705    False
1706     True
1707     True
1708     True
Length: 1709, dtype: bool

In [ ]:
#Use data selector loc -- extract duplicate rows
dataset.loc[dataset.duplicated()]

Country  year  population  life_exp   gdp_cap  year+7
1706  Tulkalam  2001        6793     90.33  1077.043    9001
1707     Halua  3002         543     90.33  3452.043    3009
1708     India  1001       12313     34.33  9809.043    1008

In [ ]:
#How can we remove duplicate row?
dataset.drop_duplicates()

Country  year  population  life_exp      gdp_cap  year+7
0     Afghanistan  1952     8425333    28.801   779.445314    1959
1     Afghanistan  1957     9240934    30.332   820.853030    1964
2     Afghanistan  1962    10267083    31.997   853.100710    1969
3     Afghanistan  1967    11537966    34.020   836.197138    1974
4     Afghanistan  1972    13079460    36.088   739.981106    1979
...           ...   ...         ...       ...          ...     ...
1701     Zimbabwe  1997    11404948    46.809   792.449960    2004
1702     Zimbabwe  2002    11926563    39.989   672.038623    2009
1703        India  1001       12313    34.330  9809.043000    1008
1704     Tulkalam  2001        6793    90.330  1077.043000    9001
1705        Halua  3002         543    90.330  3452.043000    3009

[1706 rows x 6 columns]

<b>How can we decide among all duplicate rows which ones we want to keep?</b><br>
- we can use argument keep =' ' this control how to consider duplicate value 
- It has only three distinct value
    - first
    - last
    - false
- The default is 'first'
    - if first, this considers first value as unique and rest of the same value as duplicate.
    - if last, this considers last value as unique and rest of the same values as duplicate (i.e keep the last occurance of duplicates). 
    - if False, this considers all of the same values as duplicates. All values are dropped. (all occurance of duplicate rows are removed)

In [ ]:
#looking for duplicacy only for few columns
dataset.drop_duplicates(subset=['Country'],keep='first')

Country  year  population  life_exp      gdp_cap  year+7
0     Afghanistan  1952     8425333    28.801   779.445314    1959
12        Albania  1952     1282697    55.230  1601.056136    1959
24        Algeria  1952     9279525    43.077  2449.008185    1959
36         Angola  1952     4232095    30.015  3520.610273    1959
48      Argentina  1952    17876956    62.485  5911.315053    1959
...           ...   ...         ...       ...          ...     ...
1668  Yemen, Rep.  1952     4963829    32.548   781.717576    1959
1680       Zambia  1952     2672000    42.038  1147.388831    1959
1692     Zimbabwe  1952     3080907    48.451   406.884115    1959
1704     Tulkalam  2001        6793    90.330  1077.043000    9001
1705        Halua  3002         543    90.330  3452.043000    3009

[144 rows x 6 columns]

<b>Working with rows and columns together</b>

In [ ]:
import pandas as pd 
import numpy as np 
df = pd.read_csv('mckinsey.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1704 entries, 0 to 1703
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   country     1704 non-null   object 
 1   year        1704 non-null   int64  
 2   population  1704 non-null   int64  
 3   continent   1704 non-null   object 
 4   life_exp    1704 non-null   float64
 5   gdp_cap     1704 non-null   float64
dtypes: float64(2), int64(2), object(2)
memory usage: 80.0+ KB


In [ ]:
df.iloc[1:5,1:4]

year  population continent
1  1957     9240934      Asia
2  1962    10267083      Asia
3  1967    11537966      Asia
4  1972    13079460      Asia

- pass in 2 different range for slicing
    - one for row 
    - one for column<br>
iloc doesn't include the end index while slicing

In [ ]:
df.loc[1:5,1:4] #this will throw error

In [ ]:
#we can mention ranges using column labels as well in loc
df.loc[1:10,'country':'life_exp'] #this will execute

country  year  population continent  life_exp
1   Afghanistan  1957     9240934      Asia    30.332
2   Afghanistan  1962    10267083      Asia    31.997
3   Afghanistan  1967    11537966      Asia    34.020
4   Afghanistan  1972    13079460      Asia    36.088
5   Afghanistan  1977    14880372      Asia    38.438
6   Afghanistan  1982    12881816      Asia    39.854
7   Afghanistan  1987    13867957      Asia    40.822
8   Afghanistan  1992    16317921      Asia    41.674
9   Afghanistan  1997    22227415      Asia    41.763
10  Afghanistan  2002    25268405      Asia    42.129

In [ ]:
#how can we get specific rows and columns?
df.iloc[[0,11,101],[0,2,3]] #we can specify indices packed in []

country  population continent
0    Afghanistan     8425333      Asia
11   Afghanistan    31889923      Asia
101   Bangladesh    80428306      Asia

In [ ]:
#step in slicing
df.loc[10:100:5]

country  year  population continent  life_exp       gdp_cap
10   Afghanistan  2002    25268405      Asia    42.129    726.734055
15       Albania  1967     1984060    Europe    66.220   2760.196931
20       Albania  1992     3326498    Europe    71.581   2497.437901
25       Algeria  1957    10270856    Africa    45.685   3013.976023
30       Algeria  1982    20033753    Africa    61.368   5745.160213
35       Algeria  2007    33333216    Africa    72.301   6223.367465
40        Angola  1972     5894858    Africa    37.928   5473.288005
45        Angola  1997     9875024    Africa    40.963   2277.140884
50     Argentina  1962    21283783  Americas    65.142   7133.166023
55     Argentina  1987    31620918  Americas    70.774   9139.671389
60     Australia  1952     8691212   Oceania    69.120  10039.595640
65     Australia  1977    14074100   Oceania    73.490  18334.197510
70     Australia  2002    19546792   Oceania    80.370  30687.754730
75       Austria  1967     7376998    Europe    70.140  12834.602400
80       Austria  1992     7914969    Europe    76.040  27042.018680
85       Bahrain  1957      138655      Asia    53.832  11635.799450
90       Bahrain  1982      377967      Asia    69.052  19211.147310
95       Bahrain  2007      708573      Asia    75.635  29796.048340
100   Bangladesh  1972    70759295      Asia    45.252    630.233627

<b>Pandas built-in operations</b>

In [ ]:
life_exp = df['life_exp']
life_exp

0       28.801
1       30.332
2       31.997
3       34.020
4       36.088
         ...  
1699    62.351
1700    60.377
1701    46.809
1702    39.989
1703    43.487
Name: life_exp, Length: 1704, dtype: float64

- sum()
- count()
- min()
- max()

In [ ]:
life_exp.mean(), life_exp.sum(), life_exp.count(), life_exp.min(), life_exp.max()

(59.474439366197174, 101344.44467999999, 1704, 23.599, 82.603)

<b>Sorting</b>

In [ ]:
df.sort_values(['life_exp']) #by default, values are sorted in ascending order

country  year  population continent  life_exp       gdp_cap
1292            Rwanda  1992     7290203    Africa    23.599    737.068595
0          Afghanistan  1952     8425333      Asia    28.801    779.445314
552             Gambia  1952      284320    Africa    30.000    485.230659
36              Angola  1952     4232095    Africa    30.015   3520.610273
1344      Sierra Leone  1952     2143249    Africa    30.331    879.787736
...                ...   ...         ...       ...       ...           ...
1487       Switzerland  2007     7554661    Europe    81.701  37506.419070
695            Iceland  2007      301931    Europe    81.757  36180.789190
802              Japan  2002   127065841      Asia    82.000  28604.591900
671   Hong Kong, China  2007     6980412      Asia    82.208  39724.978670
803              Japan  2007   127467972      Asia    82.603  31656.068060

[1704 rows x 6 columns]

In [ ]:
df.sort_values(by='gdp_cap',ascending=False)

country  year  population continent  life_exp        gdp_cap
853            Kuwait  1957      212846      Asia    58.033  113523.132900
856            Kuwait  1972      841934      Asia    67.712  109347.867000
852            Kuwait  1952      160000      Asia    55.565  108382.352900
854            Kuwait  1962      358266      Asia    60.470   95458.111760
855            Kuwait  1967      575003      Asia    64.624   80894.883260
..                ...   ...         ...       ...       ...            ...
333  Congo, Dem. Rep.  1997    47798986    Africa    42.587     312.188423
624     Guinea-Bissau  1952      580653    Africa    32.500     299.850319
876           Lesotho  1952      748747    Africa    42.138     298.846212
335  Congo, Dem. Rep.  2007    64606759    Africa    46.462     277.551859
334  Congo, Dem. Rep.  2002    55379852    Africa    44.966     241.165876

[1704 rows x 6 columns]

In [ ]:
#let's sort by multiple columns
df.sort_values(by=['year','life_exp'])


country  year  population continent  life_exp       gdp_cap
0          Afghanistan  1952     8425333      Asia    28.801    779.445314
552             Gambia  1952      284320    Africa    30.000    485.230659
36              Angola  1952     4232095    Africa    30.015   3520.610273
1344      Sierra Leone  1952     2143249    Africa    30.331    879.787736
1032        Mozambique  1952     6446316    Africa    31.286    468.526038
...                ...   ...         ...       ...       ...           ...
71           Australia  2007    20434176   Oceania    81.235  34435.367440
1487       Switzerland  2007     7554661    Europe    81.701  37506.419070
695            Iceland  2007      301931    Europe    81.757  36180.789190
671   Hong Kong, China  2007     6980412      Asia    82.208  39724.978670
803              Japan  2007   127467972      Asia    82.603  31656.068060

[1704 rows x 6 columns]

<b>What exactly happened here?</b><br>
- Rows were first sorted based on 'Year'
- Then, rows with same values of 'year' were sorted based on 'lifeExp'

In [ ]:
#We can have different sorting orders for different columns 
df.sort_values(by=['year','life_exp'],ascending=[False,True])

country  year  population continent  life_exp       gdp_cap
1463     Swaziland  2007     1133066    Africa    39.613   4513.480643
1043    Mozambique  2007    19951656    Africa    42.082    823.685621
1691        Zambia  2007    11746035    Africa    42.384   1271.211593
1355  Sierra Leone  2007     6144562    Africa    42.568    862.540756
887        Lesotho  2007     2012649    Africa    42.592   1569.331442
...            ...   ...         ...       ...       ...           ...
408        Denmark  1952     4334000    Europe    70.780   9692.385245
1464        Sweden  1952     7124673    Europe    71.860   8527.844662
1080   Netherlands  1952    10381988    Europe    72.130   8941.571858
684        Iceland  1952      147962    Europe    72.490   7267.688428
1140        Norway  1952     3327728    Europe    72.670  10095.421720

[1704 rows x 6 columns]

<b>Concatenating Dataframes</b>

In [ ]:
import pandas as pd
import numpy as np 
#Let's take two dataframes
users = pd.DataFrame({
    'userid' : [1,2,3,4,5],
    'name' : ['Alice','James','Luke','Steven','Rochell']
})
reaction = pd.DataFrame({
    'userid' : [1,2,2,3,4,6],
    'reaction' : ['Not So Good','Satisfied','NA','Very Satisfied','ahh! Okay','All Good']
})
rating = pd.DataFrame({
    'id' : [1,2,3,4],
    'rate' : [4,3,2,1]
})

In [ ]:
users

userid     name
0       1    Alice
1       2    James
2       3     Luke
3       4   Steven
4       5  Rochell

In [ ]:
reaction

userid        reaction
0       1     Not So Good
1       2       Satisfied
2       2              NA
3       3  Very Satisfied
4       4       ahh! Okay
5       6        All Good

In [ ]:
#concante thses 2 dataframes into a single dataframe
pd.concat([users,reaction])

userid     name        reaction
0       1    Alice             NaN
1       2    James             NaN
2       3     Luke             NaN
3       4   Steven             NaN
4       5  Rochell             NaN
0       1      NaN     Not So Good
1       2      NaN       Satisfied
2       2      NaN              NA
3       3      NaN  Very Satisfied
4       4      NaN       ahh! Okay
5       6      NaN        All Good

- by default, axis = 0 (row-wise) for concatenation
- userid, being common in both dataframe, was combined into a single column
    - First values of users df were placed, with values of column reaction as NaN
    - Then values of reaction df were placed, with values of column name as NaN
- The original indices of the rows were preserved

In [ ]:
#let's make the indices unique for each row
pd.concat([users,reaction],ignore_index=True)

userid     name        reaction
0        1    Alice             NaN
1        2    James             NaN
2        3     Luke             NaN
3        4   Steven             NaN
4        5  Rochell             NaN
5        1      NaN     Not So Good
6        2      NaN       Satisfied
7        2      NaN              NA
8        3      NaN  Very Satisfied
9        4      NaN       ahh! Okay
10       6      NaN        All Good

In [ ]:
#conncate horizontally - that is column wise
pd.concat([users,reaction],axis=1) #it gives 2 columns with different positional (implicit) index, but same label

userid     name  userid        reaction
0     1.0    Alice       1     Not So Good
1     2.0    James       2       Satisfied
2     3.0     Luke       2              NA
3     4.0   Steven       3  Very Satisfied
4     5.0  Rochell       4       ahh! Okay
5     NaN      NaN       6        All Good

<b>Merging Dataframe</b>

- <b>Difference between concat and merger</b>
    - concat
        - simply stacks multiple dataframes together along axis

    - merge 
        - combines dataframes in a smart way based on vaules in shared columns

- In concat --> simply combined/stacked the dataframe horizontally (previous example)
- userid 3 for users dataframe stacked with userid 2 for reaction dataframe
- this way of stacking doesn't help us gain any insights

In [ ]:
users

userid     name
0       1    Alice
1       2    James
2       3     Luke
3       4   Steven
4       5  Rochell

In [ ]:
reaction

userid        reaction
0       1     Not So Good
1       2       Satisfied
2       2              NA
3       3  Very Satisfied
4       4       ahh! Okay
5       6        All Good

In [ ]:
#lets join the data frame using merge()
users.merge(reaction,on='userid') #what type of join it is? Inner join

userid    name        reaction
0       1   Alice     Not So Good
1       2   James       Satisfied
2       2   James              NA
3       3    Luke  Very Satisfied
4       4  Steven       ahh! Okay

In [ ]:
#outer join - to get info of all the users and all the messages.
users.merge(reaction,on='userid',how='outer')


userid     name        reaction
0       1    Alice     Not So Good
1       2    James       Satisfied
2       2    James              NA
3       3     Luke  Very Satisfied
4       4   Steven       ahh! Okay
5       5  Rochell             NaN
6       6      NaN        All Good

In [ ]:
#left join - to get all the users in the dataframe
users.merge(reaction,on='userid',how='left')

userid     name        reaction
0       1    Alice     Not So Good
1       2    James       Satisfied
2       2    James              NA
3       3     Luke  Very Satisfied
4       4   Steven       ahh! Okay
5       5  Rochell             NaN

In [ ]:
#right join - to get all the reaction and only those user who sent a react meassage.
users.merge(reaction,on='userid',how='right')

userid    name        reaction
0       1   Alice     Not So Good
1       2   James       Satisfied
2       2   James              NA
3       3    Luke  Very Satisfied
4       4  Steven       ahh! Okay
5       6     NaN        All Good

In [ ]:
#How can we merge the 2 dataframes when the key has a different name?
#for example:
users #it has userid as key name

userid     name
0       1    Alice
1       2    James
2       3     Luke
3       4   Steven
4       5  Rochell

In [ ]:
rating  # it has id as key name

id  rate
0   1     4
1   2     3
2   3     2
3   4     1

In [ ]:
users.merge(rating,left_on='userid',right_on='id')

userid    name  id  rate
0       1   Alice   1     4
1       2   James   2     3
2       3    Luke   3     2
3       4  Steven   4     1

#### IMdb Movie Business Use-Case

- as data scientist, your task is to analyse some movie trends for the client.
- IMDB has online database of information related to movies
- the database contains several information:
    - Movies
    - Rating
    - Director
    - Popularity
    - Revenue & Budget

In [ ]:
import pandas as pd 
import numpy as np 

movies = pd.read_csv(r'C:\Users\207498\OneDrive - IBS Software Pvt Ltd\Desktop\my_work\Python\python_training\DS\DATA\movies.csv',index_col=0)
movies.head()

id     budget  popularity     revenue  \
0  43597  237000000         150  2787965087   
1  43598  300000000         139   961000000   
2  43599  245000000         107   880674609   
3  43600  250000000         112  1084939099   
5  43602  258000000         115   890871626   

                                      title  vote_average  vote_count  \
0                                    Avatar           7.2       11800   
1  Pirates of the Caribbean: At World's End           6.9        4500   
2                                   Spectre           6.3        4466   
3                     The Dark Knight Rises           7.6        9106   
5                              Spider-Man 3           5.9        3576   

   director_id  year month       day  
0         4762  2009   Dec  Thursday  
1         4763  2007   May  Saturday  
2         4764  2015   Oct    Monday  
3         4765  2012   Jul    Monday  
5         4767  2007   May   Tuesday

In [ ]:
directors = pd.read_csv(r'C:\Users\207498\OneDrive - IBS Software Pvt Ltd\Desktop\my_work\Python\python_training\DS\DATA\directors.csv',index_col=0)
directors.head()

director_name    id gender
0      James Cameron  4762   Male
1     Gore Verbinski  4763   Male
2         Sam Mendes  4764   Male
3  Christopher Nolan  4765   Male
4     Andrew Stanton  4766   Male

<b>index_col=0 explicitly states to treat the first column as the index</b>

<b>What kind of questions can we ask from this dataset?</b>
- Top 10 most popular movies, using popularity
- Find some hightest rated movies, using vote_average
- Find number of movies released per year too
- Find highest budget movies in a year using both budget and year.
- Find top 10 highest generated revenue movie.
- Total revenue generated in each year.
<hr>

- Find the most productive directors.
- Which directors produce high budget films?
- Highest and lowest rated movies for every month in a particular year.

In [ ]:
print(f'MOVIES DATAFRAME\nRows: {movies.shape[0]}\nColumns: {movies.shape[1]}')
print(f'DIRECTORS DATAFRAME\nRows: {directors.shape[0]}\nColumns: {directors.shape[1]}')

MOVIES DATAFRAME
Rows: 1465
Columns: 11
DIRECTORS DATAFRAME
Rows: 2349
Columns: 3


In [ ]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1465 entries, 0 to 4768
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   id            1465 non-null   int64  
 1   budget        1465 non-null   int64  
 2   popularity    1465 non-null   int64  
 3   revenue       1465 non-null   int64  
 4   title         1465 non-null   object 
 5   vote_average  1465 non-null   float64
 6   vote_count    1465 non-null   int64  
 7   director_id   1465 non-null   int64  
 8   year          1465 non-null   int64  
 9   month         1465 non-null   object 
 10  day           1465 non-null   object 
dtypes: float64(1), int64(7), object(3)
memory usage: 137.3+ KB


In [ ]:
directors.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2349 entries, 0 to 2348
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   director_name  2349 non-null   object
 1   id             2349 non-null   int64 
 2   gender         1724 non-null   object
dtypes: int64(1), object(2)
memory usage: 73.4+ KB


In [ ]:
movies['director_id'].nunique()

199

In [ ]:
directors['id'].nunique()

2349

- Movies dataset has only 199 unique directors
- Directors dataser has 2349 directors ( = no of rows)
- What can we infer from this?
    - Directors in movies is a subset of directors in directors dataframe

In [ ]:
#let's check whether all the directors in movies df present in directors df
movies['director_id'].isin(directors['id'])

0       True
1       True
2       True
3       True
5       True
        ... 
4736    True
4743    True
4748    True
4749    True
4768    True
Name: director_id, Length: 1465, dtype: bool

- the isin() method checks if the dataframe column column contains the specified value(s).
- How is it differ from Python 'in'?
    - 'in' works for one element at a time.
    - 'isin()' does this for all the values in the column.

In [ ]:
#Lets check if there is any False here.
np.all(movies['director_id'].isin(directors['id']))

True

- This means all the directors_id in the movies df present in the directors df.
<hr>

- Let's finally merge the dataframes

In [ ]:
data = movies.merge(directors,left_on='director_id',right_on='id',how='left')

In [ ]:
data

id_x     budget  popularity     revenue  \
0     43597  237000000         150  2787965087   
1     43598  300000000         139   961000000   
2     43599  245000000         107   880674609   
3     43600  250000000         112  1084939099   
4     43602  258000000         115   890871626   
...     ...        ...         ...         ...   
1460  48363          0           3      321952   
1461  48370      27000          19     3151130   
1462  48375          0           7           0   
1463  48376          0           3           0   
1464  48395     220000          14     2040920   

                                         title  vote_average  vote_count  \
0                                       Avatar           7.2       11800   
1     Pirates of the Caribbean: At World's End           6.9        4500   
2                                      Spectre           6.3        4466   
3                        The Dark Knight Rises           7.6        9106   
4                                 Spider-Man 3           5.9        3576   
...                                        ...           ...         ...   
1460                            The Last Waltz           7.9          64   
1461                                    Clerks           7.4         755   
1462                                   Rampage           6.0         131   
1463                                   Slacker           6.4          77   
1464                               El Mariachi           6.6         238   

      director_id  year month       day      director_name  id_y gender  
0            4762  2009   Dec  Thursday      James Cameron  4762   Male  
1            4763  2007   May  Saturday     Gore Verbinski  4763   Male  
2            4764  2015   Oct    Monday         Sam Mendes  4764   Male  
3            4765  2012   Jul    Monday  Christopher Nolan  4765   Male  
4            4767  2007   May   Tuesday          Sam Raimi  4767   Male  
...           ...   ...   ...       ...                ...   ...    ...  
1460         4809  1978   May    Monday    Martin Scorsese  4809   Male  
1461         5369  1994   Sep   Tuesday        Kevin Smith  5369   Male  
1462         5148  2009   Aug    Friday           Uwe Boll  5148   Male  
1463         5535  1990   Jul    Friday  Richard Linklater  5535   Male  
1464         5097  1992   Sep    Friday   Robert Rodriguez  5097    NaN  

[1465 rows x 14 columns]

In [ ]:
#Lets drop the redundant column
data.drop(columns=['director_id','id_y'],inplace=True)
data.rename({'id_x':'id'},axis=1,inplace=True)

<b>Feature Exploration</b>

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1465 entries, 0 to 1464
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   id             1465 non-null   int64  
 1   budget         1465 non-null   int64  
 2   popularity     1465 non-null   int64  
 3   revenue        1465 non-null   int64  
 4   title          1465 non-null   object 
 5   vote_average   1465 non-null   float64
 6   vote_count     1465 non-null   int64  
 7   year           1465 non-null   int64  
 8   month          1465 non-null   object 
 9   day            1465 non-null   object 
 10  director_name  1465 non-null   object 
 11  gender         1341 non-null   object 
dtypes: float64(1), int64(6), object(5)
memory usage: 137.5+ KB


- It looks like only gender column has some missing values.

In [ ]:
#we can describe these features to know about their range of values.
data.describe() #this gives statistical propertise of the columns
#Doesn't include those columns which have object dtype (like 'title','month')

id        budget   popularity       revenue  vote_average  \
count   1465.000000  1.465000e+03  1465.000000  1.465000e+03   1465.000000   
mean   45225.191126  4.802295e+07    30.855973  1.432539e+08      6.368191   
std     1189.096396  4.935541e+07    34.845214  2.064918e+08      0.818033   
min    43597.000000  0.000000e+00     0.000000  0.000000e+00      3.000000   
25%    44236.000000  1.400000e+07    11.000000  1.738013e+07      5.900000   
50%    45022.000000  3.300000e+07    23.000000  7.578164e+07      6.400000   
75%    45990.000000  6.600000e+07    41.000000  1.792469e+08      6.900000   
max    48395.000000  3.800000e+08   724.000000  2.787965e+09      8.300000   

         vote_count         year  
count   1465.000000  1465.000000  
mean    1146.396587  2002.615017  
std     1578.077438     8.680141  
min        1.000000  1976.000000  
25%      216.000000  1998.000000  
50%      571.000000  2004.000000  
75%     1387.000000  2009.000000  
max    13752.000000  2016.000000

In [ ]:
data.describe(include=object)

title month     day     director_name gender
count     1465  1465    1465              1465   1341
unique    1465    12       7               199      2
top     Avatar   Dec  Friday  Steven Spielberg   Male
freq         1   193     654                26   1309

In [ ]:
#lets convert the budget and revenue into million dollar USD
data['revenue'] = (data['revenue']/1000000).round(2)
data['budget'] = (data['budget']/1000000).round(2)
data.head()

id  budget  popularity  revenue  \
0  43597   237.0         150  2787.97   
1  43598   300.0         139   961.00   
2  43599   245.0         107   880.67   
3  43600   250.0         112  1084.94   
4  43602   258.0         115   890.87   

                                      title  vote_average  vote_count  year  \
0                                    Avatar           7.2       11800  2009   
1  Pirates of the Caribbean: At World's End           6.9        4500  2007   
2                                   Spectre           6.3        4466  2015   
3                     The Dark Knight Rises           7.6        9106  2012   
4                              Spider-Man 3           5.9        3576  2007   

  month       day      director_name gender  
0   Dec  Thursday      James Cameron   Male  
1   May  Saturday     Gore Verbinski   Male  
2   Oct    Monday         Sam Mendes   Male  
3   Jul    Monday  Christopher Nolan   Male  
4   May   Tuesday          Sam Raimi   Male

In [ ]:
#How many movies has rating more than 7
data.loc[data['vote_average'] > 7] 

id  budget  popularity  revenue  \
0     43597  237.00         150  2787.97   
3     43600  250.00         112  1084.94   
14    43616  250.00         120   956.02   
16    43619  250.00          94   958.40   
19    43622  200.00         100  1845.03   
...     ...     ...         ...      ...   
1456  48321    0.01          20     7.00   
1457  48323    0.00           5     0.00   
1458  48335    0.06          27     3.22   
1460  48363    0.00           3     0.32   
1461  48370    0.03          19     3.15   

                                          title  vote_average  vote_count  \
0                                        Avatar           7.2       11800   
3                         The Dark Knight Rises           7.6        9106   
14    The Hobbit: The Battle of the Five Armies           7.1        4760   
16          The Hobbit: The Desolation of Smaug           7.6        4524   
19                                      Titanic           7.5        7562   
...                                         ...           ...         ...   
1456                                 Eraserhead           7.5         485   
1457                                 The Mighty           7.1          51   
1458                                         Pi           7.1         586   
1460                             The Last Waltz           7.9          64   
1461                                     Clerks           7.4         755   

      year month        day      director_name gender  
0     2009   Dec   Thursday      James Cameron   Male  
3     2012   Jul     Monday  Christopher Nolan   Male  
14    2014   Dec  Wednesday      Peter Jackson   Male  
16    2013   Dec  Wednesday      Peter Jackson   Male  
19    1997   Nov    Tuesday      James Cameron   Male  
...    ...   ...        ...                ...    ...  
1456  1977   Mar   Saturday        David Lynch   Male  
1457  1998   Oct     Friday      Peter Chelsom   Male  
1458  1998   Jul     Friday   Darren Aronofsky   Male  
1460  1978   May     Monday    Martin Scorsese   Male  
1461  1994   Sep    Tuesday        Kevin Smith   Male  

[301 rows x 12 columns]

In [ ]:
#let say we want a subset of columns [title, director_name]
# data[data['vote_average']>7][['title','director_name']]
data.loc[data['vote_average']>7,['title','director_name','revenue']]

title      director_name  revenue
0                                        Avatar      James Cameron  2787.97
3                         The Dark Knight Rises  Christopher Nolan  1084.94
14    The Hobbit: The Battle of the Five Armies      Peter Jackson   956.02
16          The Hobbit: The Desolation of Smaug      Peter Jackson   958.40
19                                      Titanic      James Cameron  1845.03
...                                         ...                ...      ...
1456                                 Eraserhead        David Lynch     7.00
1457                                 The Mighty      Peter Chelsom     0.00
1458                                         Pi   Darren Aronofsky     3.22
1460                             The Last Waltz    Martin Scorsese     0.32
1461                                     Clerks        Kevin Smith     3.15

[301 rows x 3 columns]

In [ ]:
#which are the highly rated movies released after 2014?
data.loc[(data['vote_average']>7) & (data['year']>2014)]

id  budget  popularity  revenue                    title  \
30    43641   190.0         102  1506.25                Furious 7   
78    43724   150.0         434   378.86       Mad Max: Fury Road   
106   43773   135.0         100   532.95             The Revenant   
162   43867   108.0         167   630.16              The Martian   
312   44128    75.0          48   108.15  The Man from U.N.C.L.E.   
394   44281    44.0          68   155.76        The Hateful Eight   
625   44770    35.0          53   194.56               The Intern   
635   44784    40.0          48   165.48          Bridge of Spies   
808   45194    30.0          65    91.71                 Southpaw   
833   45293    28.0          61   201.63   Straight Outta Compton   
839   45301    28.0          57   133.35            The Big Short   
1344  47181     5.0          22    24.80                     Race   

      vote_average  vote_count  year month        day  \
30             7.3        4176  2015   Apr  Wednesday   
78             7.2        9427  2015   May  Wednesday   
106            7.3        6396  2015   Dec     Friday   
162            7.6        7268  2015   Sep  Wednesday   
312            7.1        2265  2015   Aug   Thursday   
394            7.6        4274  2015   Dec     Friday   
625            7.1        1881  2015   Sep   Thursday   
635            7.2        2583  2015   Oct   Thursday   
808            7.3        2067  2015   Jun     Monday   
833            7.7        1355  2015   Aug   Thursday   
839            7.3        2607  2015   Dec     Friday   
1344           7.1         478  2016   Feb     Friday   

                    director_name  gender  
30                      James Wan    Male  
78                  George Miller    Male  
106   Alejandro González Iñárritu    Male  
162                  Ridley Scott    Male  
312                   Guy Ritchie    Male  
394             Quentin Tarantino    Male  
625                  Nancy Meyers  Female  
635              Steven Spielberg    Male  
808                 Antoine Fuqua    Male  
833                  F. Gary Gray    Male  
839                    Adam McKay    Male  
1344              Stephen Hopkins    Male

- We cannot use 'and' or 'or' with dataframe.
- for multiple condition 
    - use elementwise operator & or |
    - for multiple conditions, we need to put each seperate condition within parenthesis()

In [ ]:
#How many movies released on either Friday or Sunday?
data.loc[(data['day']=='Friday') | (data['day']=='Sunday')]

id  budget  popularity  revenue                                title  \
22    43627  200.00          35   783.77                         Spider-Man 2   
25    43632  150.00          21   836.30  Transformers: Revenge of the Fallen   
53    43672  175.00          44   264.22                           Waterworld   
61    43696   38.00           6   207.28             The Fast and the Furious   
65    43701  160.00          21   181.67                             Poseidon   
...     ...     ...         ...      ...                                  ...   
1458  48335    0.06          27     3.22                                   Pi   
1459  48359    0.00           2     0.00                    George Washington   
1462  48375    0.00           7     0.00                              Rampage   
1463  48376    0.00           3     0.00                              Slacker   
1464  48395    0.22          14     2.04                          El Mariachi   

      vote_average  vote_count  year month     day       director_name gender  
22             6.7        4321  2004   Jun  Friday           Sam Raimi   Male  
25             6.0        3138  2009   Jun  Friday         Michael Bay   Male  
53             5.9         992  1995   Jul  Friday      Kevin Reynolds    NaN  
61             6.6        3428  2001   Jun  Friday           Rob Cohen   Male  
65             5.5         583  2006   May  Friday   Wolfgang Petersen   Male  
...            ...         ...   ...   ...     ...                 ...    ...  
1458           7.1         586  1998   Jul  Friday    Darren Aronofsky   Male  
1459           6.4          36  2000   Oct  Sunday  David Gordon Green   Male  
1462           6.0         131  2009   Aug  Friday            Uwe Boll   Male  
1463           6.4          77  1990   Jul  Friday   Richard Linklater   Male  
1464           6.6         238  1992   Sep  Friday    Robert Rodriguez    NaN  

[700 rows x 12 columns]

In [ ]:
#List top 5 most popular movies
data.sort_values(by='popularity',ascending=False).head(5)

id  budget  popularity  revenue  \
58   43692   165.0         724   675.12   
78   43724   150.0         434   378.86   
119  43796   140.0         271   655.01   
120  43797   125.0         206   752.10   
45   43662   185.0         187  1004.56   

                                                 title  vote_average  \
58                                        Interstellar           8.1   
78                                  Mad Max: Fury Road           7.2   
119  Pirates of the Caribbean: The Curse of the Bla...           7.5   
120              The Hunger Games: Mockingjay - Part 1           6.6   
45                                     The Dark Knight           8.2   

     vote_count  year month        day      director_name gender  
58        10867  2014   Nov  Wednesday  Christopher Nolan   Male  
78         9427  2015   May  Wednesday      George Miller   Male  
119        6985  2003   Jul  Wednesday     Gore Verbinski   Male  
120        5584  2014   Nov    Tuesday   Francis Lawrence   Male  
45        12002  2008   Jul  Wednesday  Christopher Nolan   Male

In [ ]:
#List all the movies directed by 'Christopher Nolan'
data.loc[data['director_name']=='James Cameron',['title']]

title
0                         Avatar
19                       Titanic
170   Terminator 2: Judgment Day
173                    True Lies
344                    The Abyss
1100                      Aliens
1320              The Terminator

In [ ]:
#List the names of female directors
data.loc[data['gender']=='Female',['director_name','title','revenue']]

director_name                        title  revenue
42        Lilly Wachowski            Jupiter Ascending   183.99
76        Lilly Wachowski       The Matrix Revolutions   424.99
77        Lilly Wachowski          The Matrix Reloaded   738.60
139       Lilly Wachowski                  Speed Racer    93.95
239          Nancy Meyers                  The Holiday   194.17
241          Nancy Meyers             It's Complicated   219.10
262          Nancy Meyers       Something's Gotta Give   266.73
361          Nancy Meyers              What Women Want   374.11
364       Lilly Wachowski                   The Matrix   463.52
602   Catherine Hardwicke              Red Riding Hood    89.16
610         Anne Fletcher                 The Proposal   317.38
625          Nancy Meyers                   The Intern   194.56
650         Anne Fletcher               The Guilt Trip    41.86
695   Catherine Hardwicke                     Twilight   392.62
724   Catherine Hardwicke           The Nativity Story     0.00
736         Anne Fletcher                  Hot Pursuit    51.68
789         Anne Fletcher                   27 Dresses   160.26
937   Catherine Hardwicke             Lords of Dogtown    13.41
971             Mira Nair                  Vanity Fair    16.12
1206        Anne Fletcher                      Step Up   114.19
1237            Mira Nair             The Perez Family     2.83
1282            Mira Nair                 The Namesake    20.14
1292    Nicole Holofcener                  Enough Said    25.29
1319    Nicole Holofcener           Friends with Money    13.37
1362      Lilly Wachowski                        Bound     7.01
1392            Mira Nair  Kama Sutra - A Tale of Love     4.11
1393    Nicole Holofcener                  Please Give     0.00
1406  Catherine Hardwicke                     Thirteen     4.60
1412  Catherine Hardwicke                        Plush     0.00
1425            Mira Nair              Monsoon Wedding     0.00
1431    Nicole Holofcener          Walking and Talking     0.00
1446    Nicole Holofcener             Lovely & Amazing     4.19

In [ ]:
#Find top 10 highest generated revenue movie.
data.sort_values(by='revenue',ascending=False).head(10).loc[:,['title','revenue','budget','director_name']]

title  revenue  budget  \
0                                           Avatar  2787.97   237.0   
19                                         Titanic  1845.03   200.0   
30                                       Furious 7  1506.25   190.0   
36                  Transformers: Dark of the Moon  1123.75   195.0   
199  The Lord of the Rings: The Return of the King  1118.89    94.0   
21                                         Skyfall  1108.56   200.0   
26                 Transformers: Age of Extinction  1091.41   210.0   
3                            The Dark Knight Rises  1084.94   250.0   
8       Pirates of the Caribbean: Dead Man's Chest  1065.66   200.0   
12     Pirates of the Caribbean: On Stranger Tides  1045.71   380.0   

         director_name  
0        James Cameron  
19       James Cameron  
30           James Wan  
36         Michael Bay  
199      Peter Jackson  
21          Sam Mendes  
26         Michael Bay  
3    Christopher Nolan  
8       Gore Verbinski  
12        Rob Marshall

- Let's encode the Gender column
    - 0 for male
    - 1 for female
- <b>apply()</b>

In [ ]:
def encode(data):
    if data == 'Male':
        return 0
    else:
        return 1

data['gender'] = data['gender'].apply(encode)
data

id  budget  popularity  revenue  \
0     43597  237.00         150  2787.97   
1     43598  300.00         139   961.00   
2     43599  245.00         107   880.67   
3     43600  250.00         112  1084.94   
4     43602  258.00         115   890.87   
...     ...     ...         ...      ...   
1460  48363    0.00           3     0.32   
1461  48370    0.03          19     3.15   
1462  48375    0.00           7     0.00   
1463  48376    0.00           3     0.00   
1464  48395    0.22          14     2.04   

                                         title  vote_average  vote_count  \
0                                       Avatar           7.2       11800   
1     Pirates of the Caribbean: At World's End           6.9        4500   
2                                      Spectre           6.3        4466   
3                        The Dark Knight Rises           7.6        9106   
4                                 Spider-Man 3           5.9        3576   
...                                        ...           ...         ...   
1460                            The Last Waltz           7.9          64   
1461                                    Clerks           7.4         755   
1462                                   Rampage           6.0         131   
1463                                   Slacker           6.4          77   
1464                               El Mariachi           6.6         238   

      year month       day      director_name  gender  
0     2009   Dec  Thursday      James Cameron       0  
1     2007   May  Saturday     Gore Verbinski       0  
2     2015   Oct    Monday         Sam Mendes       0  
3     2012   Jul    Monday  Christopher Nolan       0  
4     2007   May   Tuesday          Sam Raimi       0  
...    ...   ...       ...                ...     ...  
1460  1978   May    Monday    Martin Scorsese       0  
1461  1994   Sep   Tuesday        Kevin Smith       0  
1462  2009   Aug    Friday           Uwe Boll       0  
1463  1990   Jul    Friday  Richard Linklater       0  
1464  1992   Sep    Friday   Robert Rodriguez       1  

[1465 rows x 12 columns]

In [ ]:
#Find the sum of revenue and budget per movie
data[['revenue','budget']].sum() #this give the sum of the revenue and the budget column

revenue    209867.04
budget      70353.62
dtype: float64

In [ ]:
data[['revenue','budget']].apply(np.sum,axis=1)

0       3024.97
1       1261.00
2       1125.67
3       1334.94
4       1148.87
         ...   
1460       0.32
1461       3.18
1462       0.00
1463       0.00
1464       2.26
Length: 1465, dtype: float64

- If axis = 0 (default), it will apply to each column, if axis = 1, each row.

In [ ]:
#Let's calculate the profit per movie(revenu - budget)
def profit(x):
    return x['revenue']  - x['budget']

data['profit'] = data[['revenue','budget']].apply(profit,axis=1)

In [ ]:
data

id  budget  popularity  revenue  \
0     43597  237.00         150  2787.97   
1     43598  300.00         139   961.00   
2     43599  245.00         107   880.67   
3     43600  250.00         112  1084.94   
4     43602  258.00         115   890.87   
...     ...     ...         ...      ...   
1460  48363    0.00           3     0.32   
1461  48370    0.03          19     3.15   
1462  48375    0.00           7     0.00   
1463  48376    0.00           3     0.00   
1464  48395    0.22          14     2.04   

                                         title  vote_average  vote_count  \
0                                       Avatar           7.2       11800   
1     Pirates of the Caribbean: At World's End           6.9        4500   
2                                      Spectre           6.3        4466   
3                        The Dark Knight Rises           7.6        9106   
4                                 Spider-Man 3           5.9        3576   
...                                        ...           ...         ...   
1460                            The Last Waltz           7.9          64   
1461                                    Clerks           7.4         755   
1462                                   Rampage           6.0         131   
1463                                   Slacker           6.4          77   
1464                               El Mariachi           6.6         238   

      year month       day      director_name  gender   profit  
0     2009   Dec  Thursday      James Cameron       0  2550.97  
1     2007   May  Saturday     Gore Verbinski       0   661.00  
2     2015   Oct    Monday         Sam Mendes       0   635.67  
3     2012   Jul    Monday  Christopher Nolan       0   834.94  
4     2007   May   Tuesday          Sam Raimi       0   632.87  
...    ...   ...       ...                ...     ...      ...  
1460  1978   May    Monday    Martin Scorsese       0     0.32  
1461  1994   Sep   Tuesday        Kevin Smith       0     3.12  
1462  2009   Aug    Friday           Uwe Boll       0     0.00  
1463  1990   Jul    Friday  Richard Linklater       0     0.00  
1464  1992   Sep    Friday   Robert Rodriguez       1     1.82  

[1465 rows x 13 columns]

In [ ]:
#How can we know the number of movies released by a particular director?
data.loc[data['director_name']=='Christopher Nolan',['title']].count()

title    8
dtype: int64

In [ ]:
#What if i want to find number of movies of each director?
data['director_name'].value_counts()

director_name
Steven Spielberg      26
Martin Scorsese       19
Clint Eastwood        19
Woody Allen           18
Ridley Scott          16
                      ..
Tim Hill               5
Jonathan Liebesman     5
Roman Polanski         5
Larry Charles          5
Nicole Holofcener      5
Name: count, Length: 199, dtype: int64

In [ ]:
#Find the average popularity of each director.
data.groupby('director_name')

- It returns a DataFrameGroupBy object, not a DataFrame
- groupby('director_name') -> Grouping all rows in which director_name value is same.

In [ ]:
#Let's look at few attributes of the same 
data.groupby('director_name').ngroups #gives the number of groups our data is divided into.

199

In [ ]:
data.groupby('director_name').groups #this list down the keys or indices belong to which group

{'Adam McKay': [176, 323, 366, 505, 839, 916], 'Adam Shankman': [265, 300, 350, 404, 458, 843, 999, 1231], 'Alejandro González Iñárritu': [106, 749, 1015, 1034, 1077, 1405], 'Alex Proyas': [95, 159, 514, 671, 873], 'Alexander Payne': [793, 1006, 1101, 1211, 1281], 'Andrew Adamson': [11, 43, 328, 501, 947], 'Andrew Niccol': [533, 603, 701, 722, 1439], 'Andrzej Bartkowiak': [349, 549, 754, 911, 924], 'Andy Fickman': [517, 681, 909, 926, 973, 1023], 'Andy Tennant': [314, 320, 464, 593, 676, 885], 'Ang Lee': [99, 134, 748, 840, 1089, 1110, 1132, 1184], 'Anne Fletcher': [610, 650, 736, 789, 1206], 'Antoine Fuqua': [310, 338, 424, 467, 576, 808, 818, 1105], 'Atom Egoyan': [946, 1128, 1164, 1194, 1347, 1416], 'Barry Levinson': [313, 319, 471, 594, 878, 898, 1013, 1037, 1082, 1143, 1185, 1345, 1378], 'Barry Sonnenfeld': [13, 48, 90, 205, 591, 778, 783], 'Ben Stiller': [209, 212, 547, 562, 850], 'Bill Condon': [102, 307, 902, 1233, 1381], 'Bobby Farrelly': [352, 356, 481, 498, 624, 630, 654, 80

In [ ]:
#Let's extract data of a particular group from this list.
data.groupby('director_name').get_group('Adam McKay') #we extract data from DataFrameGroupBy object

id  budget  popularity  revenue  \
176  43882   100.0          24   170.43   
323  44151    72.5          12   162.97   
366  44236    65.0          22   128.11   
505  44503    50.0          38   173.65   
839  45301    28.0          57   133.35   
916  45443    26.0          29    90.57   

                                           title  vote_average  vote_count  \
176                               The Other Guys           6.1        1383   
323  Talladega Nights: The Ballad of Ricky Bobby           6.2         491   
366                                Step Brothers           6.5        1062   
505            Anchorman 2: The Legend Continues           6.0         923   
839                                The Big Short           7.3        2607   
916        Anchorman: The Legend of Ron Burgundy           6.7        1493   

     year month        day director_name  gender  profit  
176  2010   Aug     Friday    Adam McKay       0   70.43  
323  2006   Aug     Friday    Adam McKay       0   90.47  
366  2008   Jul     Friday    Adam McKay       0   63.11  
505  2013   Dec  Wednesday    Adam McKay       0  123.65  
839  2015   Dec     Friday    Adam McKay       0  105.35  
916  2004   Jul     Friday    Adam McKay       0   64.57

In [ ]:
data.groupby('director_name')['title'].count()

director_name
Adam McKay                      6
Adam Shankman                   8
Alejandro González Iñárritu     6
Alex Proyas                     5
Alexander Payne                 5
                               ..
Wes Craven                     10
Wolfgang Petersen               7
Woody Allen                    18
Zack Snyder                     7
Zhang Yimou                     6
Name: title, Length: 199, dtype: int64

In [ ]:
#Multiple aggregation of any feature
#Let's say - the very first and last year a director released a movie
data.groupby('director_name')['year'].aggregate(['min','max']).rename(columns={'min':'First_year','max':'Last_year'})

First_year  Last_year
director_name                                     
Adam McKay                         2004       2015
Adam Shankman                      2001       2012
Alejandro González Iñárritu        2000       2015
Alex Proyas                        1994       2016
Alexander Payne                    1999       2013
...                                 ...        ...
Wes Craven                         1984       2011
Wolfgang Petersen                  1981       2006
Woody Allen                        1977       2013
Zack Snyder                        2004       2016
Zhang Yimou                        2002       2014

[199 rows x 2 columns]

In [ ]:
#lets find the details of the movies by high budget director
data_dir_budget = data.groupby('director_name')['budget'].max().reset_index()
data_dir_budget

director_name  budget
0                     Adam McKay   100.0
1                  Adam Shankman    80.0
2    Alejandro González Iñárritu   135.0
3                    Alex Proyas   140.0
4                Alexander Payne    30.0
..                           ...     ...
194                   Wes Craven    40.0
195            Wolfgang Petersen   175.0
196                  Woody Allen    30.0
197                  Zack Snyder   250.0
198                  Zhang Yimou    94.0

[199 rows x 2 columns]

In [ ]:
names = data_dir_budget.loc[data_dir_budget['budget']>=100,'director_name']
print(names.size)
#let's filter out the movie details
data.loc[data['director_name'].isin(names)]

85


id  budget  popularity  revenue  \
0     43597  237.00         150  2787.97   
1     43598  300.00         139   961.00   
2     43599  245.00         107   880.67   
3     43600  250.00         112  1084.94   
4     43602  258.00         115   890.87   
...     ...     ...         ...      ...   
1450  48267    0.40          33   100.00   
1451  48268    0.20          13     4.51   
1452  48274    0.00           5     2.61   
1458  48335    0.06          27     3.22   
1460  48363    0.00           3     0.32   

                                         title  vote_average  vote_count  \
0                                       Avatar           7.2       11800   
1     Pirates of the Caribbean: At World's End           6.9        4500   
2                                      Spectre           6.3        4466   
3                        The Dark Knight Rises           7.6        9106   
4                                 Spider-Man 3           5.9        3576   
...                                        ...           ...         ...   
1450                                   Mad Max           6.6        1213   
1451                                  Swingers           6.8         253   
1452                                     Three           6.3          31   
1458                                        Pi           7.1         586   
1460                            The Last Waltz           7.9          64   

      year month       day      director_name  gender   profit  
0     2009   Dec  Thursday      James Cameron       0  2550.97  
1     2007   May  Saturday     Gore Verbinski       0   661.00  
2     2015   Oct    Monday         Sam Mendes       0   635.67  
3     2012   Jul    Monday  Christopher Nolan       0   834.94  
4     2007   May   Tuesday          Sam Raimi       0   632.87  
...    ...   ...       ...                ...     ...      ...  
1450  1979   Apr  Thursday      George Miller       0    99.60  
1451  1996   Oct    Friday         Doug Liman       0     4.31  
1452  2010   Dec  Thursday         Tom Tykwer       0     2.61  
1458  1998   Jul    Friday   Darren Aronofsky       0     3.16  
1460  1978   May    Monday    Martin Scorsese       0     0.32  

[679 rows x 13 columns]

<b>Group based filtering</b>

In [ ]:
#let's do it in a single go
data.groupby('director_name').filter(lambda x: x['budget'].max()>=100)

id  budget  popularity  revenue  \
0     43597  237.00         150  2787.97   
1     43598  300.00         139   961.00   
2     43599  245.00         107   880.67   
3     43600  250.00         112  1084.94   
4     43602  258.00         115   890.87   
...     ...     ...         ...      ...   
1450  48267    0.40          33   100.00   
1451  48268    0.20          13     4.51   
1452  48274    0.00           5     2.61   
1458  48335    0.06          27     3.22   
1460  48363    0.00           3     0.32   

                                         title  vote_average  vote_count  \
0                                       Avatar           7.2       11800   
1     Pirates of the Caribbean: At World's End           6.9        4500   
2                                      Spectre           6.3        4466   
3                        The Dark Knight Rises           7.6        9106   
4                                 Spider-Man 3           5.9        3576   
...                                        ...           ...         ...   
1450                                   Mad Max           6.6        1213   
1451                                  Swingers           6.8         253   
1452                                     Three           6.3          31   
1458                                        Pi           7.1         586   
1460                            The Last Waltz           7.9          64   

      year month       day      director_name  gender   profit  
0     2009   Dec  Thursday      James Cameron       0  2550.97  
1     2007   May  Saturday     Gore Verbinski       0   661.00  
2     2015   Oct    Monday         Sam Mendes       0   635.67  
3     2012   Jul    Monday  Christopher Nolan       0   834.94  
4     2007   May   Tuesday          Sam Raimi       0   632.87  
...    ...   ...       ...                ...     ...      ...  
1450  1979   Apr  Thursday      George Miller       0    99.60  
1451  1996   Oct    Friday         Doug Liman       0     4.31  
1452  2010   Dec  Thursday         Tom Tykwer       0     2.61  
1458  1998   Jul    Friday   Darren Aronofsky       0     3.16  
1460  1978   May    Monday    Martin Scorsese       0     0.32  

[679 rows x 13 columns]

- We first group data by director and then use groupby().filter function
- Groups are filtered if they do not satisfy the boolean criterion specified by function.
- this is called group based filtering
- we are filtering the groups and not the rows
- The result is not a groupby object but regular pandas dataframe with the filtered groups eliminated.

<b>Group based apply</b> - depricated soon

- Let's assume, we call a movie risky if 
    - its budget is higher than the average revenue of its diretor.

In [ ]:
# def func(x):
#     x['risky'] = x['budget'] - x['revenue'].mean() >=0
# data_risky = data.groupby('director_name',group_keys=False).apply(func)

#transform()
data['mean_revenue'] = data.groupby('director_name')['revenue'].transform('mean')
data['risky'] = data['budget'] - data['mean_revenue'] >= 0


In [ ]:
data.loc[data['risky']]

id  budget  popularity  revenue  \
7     43608   200.0         107   586.09   
12    43614   380.0         135  1045.71   
15    43618   200.0          37   310.67   
20    43624   209.0          64   303.03   
24    43630   210.0           3   459.36   
...     ...     ...         ...      ...   
1347  47224     5.0           7     3.26   
1349  47229     5.0           3     4.84   
1351  47233     5.0           6     0.00   
1356  47263    15.0          10     0.00   
1383  47453     3.5           4     0.00   

                                            title  vote_average  vote_count  \
7                               Quantum of Solace           6.1        2965   
12    Pirates of the Caribbean: On Stranger Tides           6.4        4948   
15                                     Robin Hood           6.2        1398   
20                                     Battleship           5.5        2114   
24                          X-Men: The Last Stand           6.3        3525   
...                                           ...           ...         ...   
1347                          The Sweet Hereafter           6.8         103   
1349                         90 Minutes in Heaven           5.4          40   
1351                                Light Sleeper           5.7          15   
1356                           Dying of the Light           4.5         118   
1383                  In the Name of the King III           3.3          19   

      year month        day   director_name  gender  profit  mean_revenue  \
7     2008   Oct   Thursday    Marc Forster       0  386.09    176.136250   
12    2011   May   Saturday    Rob Marshall       0  665.71    356.292000   
15    2010   May  Wednesday    Ridley Scott       0  110.67    199.346875   
20    2012   Apr  Wednesday      Peter Berg       0   94.03    208.973333   
24    2006   May  Wednesday    Brett Ratner       0  249.36    192.398889   
...    ...   ...        ...             ...     ...     ...           ...   
1347  1997   May  Wednesday     Atom Egoyan       0   -1.74      1.953333   
1349  2015   Sep     Friday  Michael Polish       0   -0.16      3.194000   
1351  1992   Aug     Friday   Paul Schrader       1   -5.00      0.353333   
1356  2014   Dec   Thursday   Paul Schrader       1  -15.00      0.353333   
1383  2013   Dec     Friday        Uwe Boll       0   -3.50      2.570000   

      risky  
7      True  
12     True  
15     True  
20     True  
24     True  
...     ...  
1347   True  
1349   True  
1351   True  
1356   True  
1383   True  

[131 rows x 15 columns]

<b>Multi-Indexing</b>

- Which director would you be considered as most productive?
    - decide based on the number of movies released by a director.
    - consider quality into consideration
    - consider the amount of business the movie is doing.

In [ ]:
#let's calculate who has directed maximum number of movies
data.groupby('director_name')['title'].count().sort_values(ascending=False)

director_name
Steven Spielberg    26
Clint Eastwood      19
Martin Scorsese     19
Woody Allen         18
Robert Rodriguez    16
                    ..
Paul Weitz           5
John Madden          5
Paul Verhoeven       5
John Whitesell       5
Kevin Reynolds       5
Name: title, Length: 199, dtype: int64

In [ ]:
data_agg = data.groupby(['director_name'])[['year','title']].aggregate({
    'year':['min','max'],
    'title':'count'
    })
data_agg

year       title
                              min   max count
director_name                                
Adam McKay                   2004  2015     6
Adam Shankman                2001  2012     8
Alejandro González Iñárritu  2000  2015     6
Alex Proyas                  1994  2016     5
Alexander Payne              1999  2013     5
...                           ...   ...   ...
Wes Craven                   1984  2011    10
Wolfgang Petersen            1981  2006     7
Woody Allen                  1977  2013    18
Zack Snyder                  2004  2016     7
Zhang Yimou                  2002  2014     6

[199 rows x 3 columns]

- director_name column has turned into row labels.
- There are multiple levels for the column names.
- <b>This is called Multi-index dataframe</b><br><br>
<b>What is Multi-index dataframe?</b>
- It can have multiple indexes along a dimension.
    - no. of dimension remain same though ie 2D
- multi-level index are possible both for rows and columns

In [ ]:
data_agg.columns

MultiIndex([( 'year',   'min'),
            ( 'year',   'max'),
            ('title', 'count')],
           )

here, the level-1 column names are year and title

In [ ]:
#lets print the year column of this multi-index dataframe
data_agg['year']

min   max
director_name                          
Adam McKay                   2004  2015
Adam Shankman                2001  2012
Alejandro González Iñárritu  2000  2015
Alex Proyas                  1994  2016
Alexander Payne              1999  2013
...                           ...   ...
Wes Craven                   1984  2011
Wolfgang Petersen            1981  2006
Woody Allen                  1977  2013
Zack Snyder                  2004  2016
Zhang Yimou                  2002  2014

[199 rows x 2 columns]

In [ ]:
#lets convert multi-level back to only one level of columns
data_agg.columns = ['_'.join(col) for col in data_agg.columns]
data_agg

year_min  year_max  title_count
director_name                                               
Adam McKay                       2004      2015            6
Adam Shankman                    2001      2012            8
Alejandro González Iñárritu      2000      2015            6
Alex Proyas                      1994      2016            5
Alexander Payne                  1999      2013            5
...                               ...       ...          ...
Wes Craven                       1984      2011           10
Wolfgang Petersen                1981      2006            7
Woody Allen                      1977      2013           18
Zack Snyder                      2004      2016            7
Zhang Yimou                      2002      2014            6

[199 rows x 3 columns]

In [ ]:
#another way
data.groupby('director_name')[['year','title']].aggregate(
    year_max = ('year','max'),
    year_min = ('year','min'),
    title_count = ('title','count')
)

year_max  year_min  title_count
director_name                                               
Adam McKay                       2015      2004            6
Adam Shankman                    2012      2001            8
Alejandro González Iñárritu      2015      2000            6
Alex Proyas                      2016      1994            5
Alexander Payne                  2013      1999            5
...                               ...       ...          ...
Wes Craven                       2011      1984           10
Wolfgang Petersen                2006      1981            7
Woody Allen                      2013      1977           18
Zack Snyder                      2016      2004            7
Zhang Yimou                      2014      2002            6

[199 rows x 3 columns]

In [ ]:
#lets calculate how many years the director has been active
data_agg['active_year'] = data_agg['year_max'] - data_agg['year_min']
data_agg

year_min  year_max  title_count  active_year
director_name                                                            
Adam McKay                       2004      2015            6           11
Adam Shankman                    2001      2012            8           11
Alejandro González Iñárritu      2000      2015            6           15
Alex Proyas                      1994      2016            5           22
Alexander Payne                  1999      2013            5           14
...                               ...       ...          ...          ...
Wes Craven                       1984      2011           10           27
Wolfgang Petersen                1981      2006            7           25
Woody Allen                      1977      2013           18           36
Zack Snyder                      2004      2016            7           12
Zhang Yimou                      2002      2014            6           12

[199 rows x 4 columns]

In [ ]:
#calculate the rate of directing movies by title_count/active_year
data_agg['movies_per_year'] = data_agg['title_count'] / data_agg['active_year']
data_agg

year_min  year_max  title_count  active_year  \
director_name                                                               
Adam McKay                       2004      2015            6           11   
Adam Shankman                    2001      2012            8           11   
Alejandro González Iñárritu      2000      2015            6           15   
Alex Proyas                      1994      2016            5           22   
Alexander Payne                  1999      2013            5           14   
...                               ...       ...          ...          ...   
Wes Craven                       1984      2011           10           27   
Wolfgang Petersen                1981      2006            7           25   
Woody Allen                      1977      2013           18           36   
Zack Snyder                      2004      2016            7           12   
Zhang Yimou                      2002      2014            6           12   

                             movies_per_year  
director_name                                 
Adam McKay                          0.545455  
Adam Shankman                       0.727273  
Alejandro González Iñárritu         0.400000  
Alex Proyas                         0.227273  
Alexander Payne                     0.357143  
...                                      ...  
Wes Craven                          0.370370  
Wolfgang Petersen                   0.280000  
Woody Allen                         0.500000  
Zack Snyder                         0.583333  
Zhang Yimou                         0.500000  

[199 rows x 5 columns]

In [ ]:
data_agg.sort_values('movies_per_year',ascending=False)

year_min  year_max  title_count  active_year  \
director_name                                                    
Tyler Perry           2006      2013            9            7   
Jason Friedberg       2006      2010            5            4   
Shawn Levy            2002      2014           11           12   
Robert Rodriguez      1992      2014           16           22   
Adam Shankman         2001      2012            8           11   
...                    ...       ...          ...          ...   
Lawrence Kasdan       1985      2012            5           27   
Luc Besson            1985      2014            5           29   
Robert Redford        1980      2010            5           30   
Sidney Lumet          1976      2006            5           30   
Michael Apted         1980      2010            5           30   

                  movies_per_year  
director_name                      
Tyler Perry              1.285714  
Jason Friedberg          1.250000  
Shawn Levy               0.916667  
Robert Rodriguez         0.727273  
Adam Shankman            0.727273  
...                           ...  
Lawrence Kasdan          0.185185  
Luc Besson               0.172414  
Robert Redford           0.166667  
Sidney Lumet             0.166667  
Michael Apted            0.166667  

[199 rows x 5 columns]

- from the analysis 'Tyler Perry' turns out to be the truly productive director in number of movies.

#### Use Case -2

- Dataset : data of few drugs being developed by PFizer
- Columns info:
    - Data
    - Drug_name
    - Parameter (Temperature, Pressure)
    - This parameters are recorded after an interval of 1 hour everyday to monitor the drug stability in a drug development test.
- These data points are thus used to identify the optimal set of values of parameters for the stabilty of the drugs.

In [ ]:
import numpy as np 
import pandas as pd

df =  pd.read_csv(r'C:\Users\207498\OneDrive - IBS Software Pvt Ltd\Desktop\my_work\Python\python_training\DS\DATA\Pfizer_1.csv')
df

Date                Drug_Name    Parameter  1:30:00  2:30:00  \
0   15-10-2020  diltiazem hydrochloride  Temperature     23.0     22.0   
1   15-10-2020  diltiazem hydrochloride     Pressure     12.0     13.0   
2   15-10-2020      docetaxel injection  Temperature      NaN     17.0   
3   15-10-2020      docetaxel injection     Pressure      NaN     22.0   
4   15-10-2020   ketamine hydrochloride  Temperature     24.0      NaN   
5   15-10-2020   ketamine hydrochloride     Pressure      8.0      NaN   
6   16-10-2020  diltiazem hydrochloride  Temperature     34.0     35.0   
7   16-10-2020  diltiazem hydrochloride     Pressure     18.0     19.0   
8   16-10-2020      docetaxel injection  Temperature     46.0     47.0   
9   16-10-2020      docetaxel injection     Pressure     23.0     24.0   
10  16-10-2020   ketamine hydrochloride  Temperature      8.0      9.0   
11  16-10-2020   ketamine hydrochloride     Pressure     12.0     12.0   
12  17-10-2020  diltiazem hydrochloride  Temperature     20.0     19.0   
13  17-10-2020  diltiazem hydrochloride     Pressure      3.0      4.0   
14  17-10-2020      docetaxel injection  Temperature     12.0     13.0   
15  17-10-2020      docetaxel injection     Pressure     20.0     22.0   
16  17-10-2020   ketamine hydrochloride  Temperature     13.0     14.0   
17  17-10-2020   ketamine hydrochloride     Pressure      8.0      9.0   

    3:30:00  4:30:00  5:30:00  6:30:00  7:30:00  8:30:00  9:30:00  10:30:00  \
0       NaN     21.0     21.0       22     23.0     21.0     22.0        20   
1       NaN     11.0     13.0       14     16.0     16.0     24.0        18   
2      18.0      NaN     17.0       18      NaN      NaN     23.0        23   
3      22.0      NaN     22.0       23      NaN      NaN     27.0        26   
4       NaN     27.0      NaN       26     25.0     24.0     23.0        22   
5       NaN      7.0      NaN        9     10.0     11.0     10.0         9   
6      36.0     36.0     37.0       38     37.0     38.0     39.0        40   
7      20.0     21.0     22.0       23     24.0     25.0     25.0        24   
8       NaN     48.0     48.0       49     50.0     52.0     55.0        56   
9       NaN     25.0     26.0       27     28.0     29.0     28.0        28   
10     10.0      NaN     11.0       12     12.0     11.0      NaN        13   
11     13.0      NaN     15.0       15     15.0     15.0      NaN        16   
12     19.0     18.0     17.0       16     15.0      NaN     13.0        14   
13      4.0      4.0      6.0        8      9.0      NaN      9.0        11   
14     14.0     15.0     16.0       17     18.0     19.0     20.0        21   
15     22.0     22.0     22.0       23     25.0     26.0     27.0        28   
16     15.0     16.0     17.0       18     19.0     20.0     21.0        22   
17     10.0     11.0     11.0       12     12.0     11.0     12.0        13   

    11:30:00  12:30:00  
0       20.0        21  
1       19.0        20  
2       25.0        25  
3       29.0        28  
4       21.0        20  
5        9.0        11  
6        NaN        42  
7        NaN        27  
8       57.0        58  
9       29.0        30  
10      14.0        15  
11      17.0        18  
12      11.0        10  
13      13.0        14  
14      22.0        23  
15      29.0        28  
16      23.0        24  
17      14.0        15

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 15 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Date       18 non-null     object 
 1   Drug_Name  18 non-null     object 
 2   Parameter  18 non-null     object 
 3   1:30:00    16 non-null     float64
 4   2:30:00    16 non-null     float64
 5   3:30:00    12 non-null     float64
 6   4:30:00    14 non-null     float64
 7   5:30:00    16 non-null     float64
 8   6:30:00    18 non-null     int64  
 9   7:30:00    16 non-null     float64
 10  8:30:00    14 non-null     float64
 11  9:30:00    16 non-null     float64
 12  10:30:00   18 non-null     int64  
 13  11:30:00   16 non-null     float64
 14  12:30:00   18 non-null     int64  
dtypes: float64(9), int64(3), object(3)
memory usage: 2.2+ KB


<b>Melting in Pandas</b>

- How can we restructure our data into having every row corresponding to a single reading?
- Trasform or reshape a Dataframe from a wide format to a long format.

In [ ]:
pd.melt(df,id_vars=['Date','Parameter','Drug_Name'])

Date    Parameter                Drug_Name  variable  value
0    15-10-2020  Temperature  diltiazem hydrochloride   1:30:00   23.0
1    15-10-2020     Pressure  diltiazem hydrochloride   1:30:00   12.0
2    15-10-2020  Temperature      docetaxel injection   1:30:00    NaN
3    15-10-2020     Pressure      docetaxel injection   1:30:00    NaN
4    15-10-2020  Temperature   ketamine hydrochloride   1:30:00   24.0
..          ...          ...                      ...       ...    ...
211  17-10-2020     Pressure  diltiazem hydrochloride  12:30:00   14.0
212  17-10-2020  Temperature      docetaxel injection  12:30:00   23.0
213  17-10-2020     Pressure      docetaxel injection  12:30:00   28.0
214  17-10-2020  Temperature   ketamine hydrochloride  12:30:00   24.0
215  17-10-2020     Pressure   ketamine hydrochloride  12:30:00   15.0

[216 rows x 5 columns]

- the hourly interval columns restructed into a better format.
- Here, we have a column for time(varible), with timestamps as the column value.
- 'Melt' timestamp columns into two columns - timestamp and corresponding value.

- pd.melt()
- This convert our data from wide to long format
- id_vars = [] are set of varibles which remain unmelted.

In [ ]:
data_melt = pd.melt(df,id_vars=['Date','Drug_Name','Parameter'],
                    var_name='Time',
                    value_name='Reading')
data_melt

Date                Drug_Name    Parameter      Time  Reading
0    15-10-2020  diltiazem hydrochloride  Temperature   1:30:00     23.0
1    15-10-2020  diltiazem hydrochloride     Pressure   1:30:00     12.0
2    15-10-2020      docetaxel injection  Temperature   1:30:00      NaN
3    15-10-2020      docetaxel injection     Pressure   1:30:00      NaN
4    15-10-2020   ketamine hydrochloride  Temperature   1:30:00     24.0
..          ...                      ...          ...       ...      ...
211  17-10-2020  diltiazem hydrochloride     Pressure  12:30:00     14.0
212  17-10-2020      docetaxel injection  Temperature  12:30:00     23.0
213  17-10-2020      docetaxel injection     Pressure  12:30:00     28.0
214  17-10-2020   ketamine hydrochloride  Temperature  12:30:00     24.0
215  17-10-2020   ketamine hydrochloride     Pressure  12:30:00     15.0

[216 rows x 5 columns]

- The labels of the timestamp columns are conviniently melted into a single column - time
- It retained all values in column reading

<b>Pivot</b>

In [ ]:
#How we can restructure our data back to the original wide format, before it was melted?
data_melt.pivot(index=['Date','Drug_Name','Parameter'], #labels to use to make new frame's index
                columns='Time', #Labels to use to make new frame's column
                values='Reading') # values to use for populating new frame's values

Time                                            10:30:00  11:30:00  12:30:00  \
Date       Drug_Name               Parameter                                   
15-10-2020 diltiazem hydrochloride Pressure         18.0      19.0      20.0   
                                   Temperature      20.0      20.0      21.0   
           docetaxel injection     Pressure         26.0      29.0      28.0   
                                   Temperature      23.0      25.0      25.0   
           ketamine hydrochloride  Pressure          9.0       9.0      11.0   
                                   Temperature      22.0      21.0      20.0   
16-10-2020 diltiazem hydrochloride Pressure         24.0       NaN      27.0   
                                   Temperature      40.0       NaN      42.0   
           docetaxel injection     Pressure         28.0      29.0      30.0   
                                   Temperature      56.0      57.0      58.0   
           ketamine hydrochloride  Pressure         16.0      17.0      18.0   
                                   Temperature      13.0      14.0      15.0   
17-10-2020 diltiazem hydrochloride Pressure         11.0      13.0      14.0   
                                   Temperature      14.0      11.0      10.0   
           docetaxel injection     Pressure         28.0      29.0      28.0   
                                   Temperature      21.0      22.0      23.0   
           ketamine hydrochloride  Pressure         13.0      14.0      15.0   
                                   Temperature      22.0      23.0      24.0   

Time                                            1:30:00  2:30:00  3:30:00  \
Date       Drug_Name               Parameter                                
15-10-2020 diltiazem hydrochloride Pressure        12.0     13.0      NaN   
                                   Temperature     23.0     22.0      NaN   
           docetaxel injection     Pressure         NaN     22.0     22.0   
                                   Temperature      NaN     17.0     18.0   
           ketamine hydrochloride  Pressure         8.0      NaN      NaN   
                                   Temperature     24.0      NaN      NaN   
16-10-2020 diltiazem hydrochloride Pressure        18.0     19.0     20.0   
                                   Temperature     34.0     35.0     36.0   
           docetaxel injection     Pressure        23.0     24.0      NaN   
                                   Temperature     46.0     47.0      NaN   
           ketamine hydrochloride  Pressure        12.0     12.0     13.0   
                                   Temperature      8.0      9.0     10.0   
17-10-2020 diltiazem hydrochloride Pressure         3.0      4.0      4.0   
                                   Temperature     20.0     19.0     19.0   
           docetaxel injection     Pressure        20.0     22.0     22.0   
                                   Temperature     12.0     13.0     14.0   
           ketamine hydrochloride  Pressure         8.0      9.0     10.0   
                                   Temperature     13.0     14.0     15.0   

Time                                            4:30:00  5:30:00  6:30:00  \
Date       Drug_Name               Parameter                                
15-10-2020 diltiazem hydrochloride Pressure        11.0     13.0     14.0   
                                   Temperature     21.0     21.0     22.0   
           docetaxel injection     Pressure         NaN     22.0     23.0   
                                   Temperature      NaN     17.0     18.0   
           ketamine hydrochloride  Pressure         7.0      NaN      9.0   
                                   Temperature     27.0      NaN     26.0   
16-10-2020 diltiazem hydrochloride Pressure        21.0     22.0     23.0   
                                   Temperature     36.0     37.0     38.0   
           docetaxel injection     Pressure        25.0     26.0     27.0   
           

In [ ]:
#We are getting multiple indices here
data_melt.pivot(index=['Date','Drug_Name','Parameter'], 
                columns='Time', 
                values='Reading').reset_index()

Time        Date                Drug_Name    Parameter  10:30:00  11:30:00  \
0     15-10-2020  diltiazem hydrochloride     Pressure      18.0      19.0   
1     15-10-2020  diltiazem hydrochloride  Temperature      20.0      20.0   
2     15-10-2020      docetaxel injection     Pressure      26.0      29.0   
3     15-10-2020      docetaxel injection  Temperature      23.0      25.0   
4     15-10-2020   ketamine hydrochloride     Pressure       9.0       9.0   
5     15-10-2020   ketamine hydrochloride  Temperature      22.0      21.0   
6     16-10-2020  diltiazem hydrochloride     Pressure      24.0       NaN   
7     16-10-2020  diltiazem hydrochloride  Temperature      40.0       NaN   
8     16-10-2020      docetaxel injection     Pressure      28.0      29.0   
9     16-10-2020      docetaxel injection  Temperature      56.0      57.0   
10    16-10-2020   ketamine hydrochloride     Pressure      16.0      17.0   
11    16-10-2020   ketamine hydrochloride  Temperature      13.0      14.0   
12    17-10-2020  diltiazem hydrochloride     Pressure      11.0      13.0   
13    17-10-2020  diltiazem hydrochloride  Temperature      14.0      11.0   
14    17-10-2020      docetaxel injection     Pressure      28.0      29.0   
15    17-10-2020      docetaxel injection  Temperature      21.0      22.0   
16    17-10-2020   ketamine hydrochloride     Pressure      13.0      14.0   
17    17-10-2020   ketamine hydrochloride  Temperature      22.0      23.0   

Time  12:30:00  1:30:00  2:30:00  3:30:00  4:30:00  5:30:00  6:30:00  7:30:00  \
0         20.0     12.0     13.0      NaN     11.0     13.0     14.0     16.0   
1         21.0     23.0     22.0      NaN     21.0     21.0     22.0     23.0   
2         28.0      NaN     22.0     22.0      NaN     22.0     23.0      NaN   
3         25.0      NaN     17.0     18.0      NaN     17.0     18.0      NaN   
4         11.0      8.0      NaN      NaN      7.0      NaN      9.0     10.0   
5         20.0     24.0      NaN      NaN     27.0      NaN     26.0     25.0   
6         27.0     18.0     19.0     20.0     21.0     22.0     23.0     24.0   
7         42.0     34.0     35.0     36.0     36.0     37.0     38.0     37.0   
8         30.0     23.0     24.0      NaN     25.0     26.0     27.0     28.0   
9         58.0     46.0     47.0      NaN     48.0     48.0     49.0     50.0   
10        18.0     12.0     12.0     13.0      NaN     15.0     15.0     15.0   
11        15.0      8.0      9.0     10.0      NaN     11.0     12.0     12.0   
12        14.0      3.0      4.0      4.0      4.0      6.0      8.0      9.0   
13        10.0     20.0     19.0     19.0     18.0     17.0     16.0     15.0   
14        28.0     20.0     22.0     22.0     22.0     22.0     23.0     25.0   
15        23.0     12.0     13.0     14.0     15.0     16.0     17.0     18.0   
16        15.0      8.0      9.0     10.0     11.0     11.0     12.0     12.0   
17        24.0     13.0     14.0     15.0     16.0     17.0     18.0     19.0   

Time  8:30:00  9:30:00  
0        16.0     24.0  
1        21.0     22.0  
2         NaN     27.0  
3         NaN     23.0  
4        11.0     10.0  
5        24.0     23.0  
6        25.0     25.0  
7        38.0     39.0  
8        29.0     28.0  
9        52.0     55.0  
10       15.0      NaN  
11       11.0      NaN  
12        NaN      9.0  
13        NaN     13.0  
14       26.0     27.0  
15       19.0     20.0  
16       11.0     12.0  
17       20.0     21.0

- pivot() is the exact opposite of melt

In [204]:
#Can we further resturcture our data into dividing the parameter column into Temperature and Pressure?
#We want tot split one single column into multiple columns
data_tidy = data_melt.pivot(index=['Date','Time','Drug_Name'],
                            columns='Parameter',
                            values='Reading')
data_tidy

Parameter                                    Pressure  Temperature
Date       Time     Drug_Name                                     
15-10-2020 10:30:00 diltiazem hydrochloride      18.0         20.0
                    docetaxel injection          26.0         23.0
                    ketamine hydrochloride        9.0         22.0
           11:30:00 diltiazem hydrochloride      19.0         20.0
                    docetaxel injection          29.0         25.0
...                                               ...          ...
17-10-2020 8:30:00  docetaxel injection          26.0         19.0
                    ketamine hydrochloride       11.0         20.0
           9:30:00  diltiazem hydrochloride       9.0         13.0
                    docetaxel injection          27.0         20.0
                    ketamine hydrochloride       12.0         21.0

[108 rows x 2 columns]

In [205]:
data_tidy = data_tidy.reset_index()

In [206]:
data_tidy.columns

Index(['Date', 'Time', 'Drug_Name', 'Pressure', 'Temperature'], dtype='object', name='Parameter')

In [207]:
data_tidy.columns.name = 'None'

In [208]:
data_tidy

None        Date      Time                Drug_Name  Pressure  Temperature
0     15-10-2020  10:30:00  diltiazem hydrochloride      18.0         20.0
1     15-10-2020  10:30:00      docetaxel injection      26.0         23.0
2     15-10-2020  10:30:00   ketamine hydrochloride       9.0         22.0
3     15-10-2020  11:30:00  diltiazem hydrochloride      19.0         20.0
4     15-10-2020  11:30:00      docetaxel injection      29.0         25.0
..           ...       ...                      ...       ...          ...
103   17-10-2020   8:30:00      docetaxel injection      26.0         19.0
104   17-10-2020   8:30:00   ketamine hydrochloride      11.0         20.0
105   17-10-2020   9:30:00  diltiazem hydrochloride       9.0         13.0
106   17-10-2020   9:30:00      docetaxel injection      27.0         20.0
107   17-10-2020   9:30:00   ketamine hydrochloride      12.0         21.0

[108 rows x 5 columns]

In [ ]:
#How we can get day-wise mean value of temperature for each drug?
pd.pivot_table(data_tidy,
               index=['Drug_Name'],
               columns='Date',
               values=['Temperature'],
               aggfunc='mean')


None                    Temperature                      
Date                     15-10-2020 16-10-2020 17-10-2020
Drug_Name                                                
diltiazem hydrochloride   21.454545  37.454545  15.636364
docetaxel injection       20.750000  51.454545  17.500000
ketamine hydrochloride    23.555556  11.500000  18.500000

<b>pivot_table()</b>
- Work same as pivot() 
- as an extra parameter, we pass the type of aggregator
- pivot_table uses groupby() in the backend to group the data and perform the aggregration.

In [ ]:
#similarly, if we want to find the minimum and maximum vaules of temperature and pressure on a particular data.
pd.pivot_table(data_tidy,
               index='Drug_Name',
               columns='Date',
               values=['Temperature','Pressure'],
               aggfunc=['min','max'])

min                                    \
None                      Pressure                       Temperature   
Date                    15-10-2020 16-10-2020 17-10-2020  15-10-2020   
Drug_Name                                                              
diltiazem hydrochloride       11.0       18.0        3.0        20.0   
docetaxel injection           22.0       23.0       20.0        17.0   
ketamine hydrochloride         7.0       12.0        8.0        20.0   

                                                     max             \
None                                            Pressure              
Date                    16-10-2020 17-10-2020 15-10-2020 16-10-2020   
Drug_Name                                                             
diltiazem hydrochloride       34.0       10.0       24.0       27.0   
docetaxel injection           46.0       12.0       29.0       30.0   
ketamine hydrochloride         8.0       13.0       11.0       18.0   

                                                                      
None                               Temperature                        
Date                    17-10-2020  15-10-2020 16-10-2020 17-10-2020  
Drug_Name                                                             
diltiazem hydrochloride       14.0        23.0       42.0       20.0  
docetaxel injection           29.0        25.0       58.0       23.0  
ketamine hydrochloride        15.0        27.0       15.0       24.0

<b>Handling Missing Values</b>

In [ ]:
data_tidy

None        Date      Time                Drug_Name  Pressure  Temperature
0     15-10-2020  10:30:00  diltiazem hydrochloride      18.0         20.0
1     15-10-2020  10:30:00      docetaxel injection      26.0         23.0
2     15-10-2020  10:30:00   ketamine hydrochloride       9.0         22.0
3     15-10-2020  11:30:00  diltiazem hydrochloride      19.0         20.0
4     15-10-2020  11:30:00      docetaxel injection      29.0         25.0
..           ...       ...                      ...       ...          ...
103   17-10-2020   8:30:00      docetaxel injection      26.0         19.0
104   17-10-2020   8:30:00   ketamine hydrochloride      11.0         20.0
105   17-10-2020   9:30:00  diltiazem hydrochloride       9.0         13.0
106   17-10-2020   9:30:00      docetaxel injection      27.0         20.0
107   17-10-2020   9:30:00   ketamine hydrochloride      12.0         21.0

[108 rows x 5 columns]

- What are missing values?
    - A missing value signifies an empty cell/no data
    - there can be 2 kinds of missing values:
        - None
        - NaN (Not a Number)

In [ ]:
#difference between NaN and None - different lies in their data type
type(None)

NoneType

In [ ]:
type(np.nan)

float

None type is for missing values in a column with non-number entries
- eg strings <br>
NaN occurs for columns with number entries

Pandas uses these values nearly interchangeably, converting between them where appropriate, based on column datatype.

In [ ]:
pd.Series([1,np.nan,2,None]) #For numerical types, Pandas changes None to NaN type

0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

In [ ]:
pd.Series(['1','np.nan','2',None]) #For object types, the None is preserved and not changed to NaN

0         1
1    np.nan
2         2
3      None
dtype: object

In [ ]:
pd.Series(['1','np.nan','2',np.nan])

0         1
1    np.nan
2         2
3       NaN
dtype: object

In [ ]:
#How to know thw count of missing values for each row/column?
df.isna()

Date  Drug_Name  Parameter  1:30:00  2:30:00  3:30:00  4:30:00  5:30:00  \
0   False      False      False    False    False     True    False    False   
1   False      False      False    False    False     True    False    False   
2   False      False      False     True    False    False     True    False   
3   False      False      False     True    False    False     True    False   
4   False      False      False    False     True     True    False     True   
5   False      False      False    False     True     True    False     True   
6   False      False      False    False    False    False    False    False   
7   False      False      False    False    False    False    False    False   
8   False      False      False    False    False     True    False    False   
9   False      False      False    False    False     True    False    False   
10  False      False      False    False    False    False     True    False   
11  False      False      False    False    False    False     True    False   
12  False      False      False    False    False    False    False    False   
13  False      False      False    False    False    False    False    False   
14  False      False      False    False    False    False    False    False   
15  False      False      False    False    False    False    False    False   
16  False      False      False    False    False    False    False    False   
17  False      False      False    False    False    False    False    False   

    6:30:00  7:30:00  8:30:00  9:30:00  10:30:00  11:30:00  12:30:00  
0     False    False    False    False     False     False     False  
1     False    False    False    False     False     False     False  
2     False     True     True    False     False     False     False  
3     False     True     True    False     False     False     False  
4     False    False    False    False     False     False     False  
5     False    False    False    False     False     False     False  
6     False    False    False    False     False      True     False  
7     False    False    False    False     False      True     False  
8     False    False    False    False     False     False     False  
9     False    False    False    False     False     False     False  
10    False    False    False     True     False     False     False  
11    False    False    False     True     False     False     False  
12    False    False     True    False     False     False     False  
13    False    False     True    False     False     False     False  
14    False    False    False    False     False     False     False  
15    False    False    False    False     False     False     False  
16    False    False    False    False     False     False     False  
17    False    False    False    False     False     False     False

In [ ]:
df.isnull()

Date  Drug_Name  Parameter  1:30:00  2:30:00  3:30:00  4:30:00  5:30:00  \
0   False      False      False    False    False     True    False    False   
1   False      False      False    False    False     True    False    False   
2   False      False      False     True    False    False     True    False   
3   False      False      False     True    False    False     True    False   
4   False      False      False    False     True     True    False     True   
5   False      False      False    False     True     True    False     True   
6   False      False      False    False    False    False    False    False   
7   False      False      False    False    False    False    False    False   
8   False      False      False    False    False     True    False    False   
9   False      False      False    False    False     True    False    False   
10  False      False      False    False    False    False     True    False   
11  False      False      False    False    False    False     True    False   
12  False      False      False    False    False    False    False    False   
13  False      False      False    False    False    False    False    False   
14  False      False      False    False    False    False    False    False   
15  False      False      False    False    False    False    False    False   
16  False      False      False    False    False    False    False    False   
17  False      False      False    False    False    False    False    False   

    6:30:00  7:30:00  8:30:00  9:30:00  10:30:00  11:30:00  12:30:00  
0     False    False    False    False     False     False     False  
1     False    False    False    False     False     False     False  
2     False     True     True    False     False     False     False  
3     False     True     True    False     False     False     False  
4     False    False    False    False     False     False     False  
5     False    False    False    False     False     False     False  
6     False    False    False    False     False      True     False  
7     False    False    False    False     False      True     False  
8     False    False    False    False     False     False     False  
9     False    False    False    False     False     False     False  
10    False    False    False     True     False     False     False  
11    False    False    False     True     False     False     False  
12    False    False     True    False     False     False     False  
13    False    False     True    False     False     False     False  
14    False    False    False    False     False     False     False  
15    False    False    False    False     False     False     False  
16    False    False    False    False     False     False     False  
17    False    False    False    False     False     False     False

isna() and isnull() both the functiona have same function signature

In [ ]:
df.isna().sum() #On top of this we can use .sum() to find the count

Date         0
Drug_Name    0
Parameter    0
1:30:00      2
2:30:00      2
3:30:00      6
4:30:00      4
5:30:00      2
6:30:00      0
7:30:00      2
8:30:00      4
9:30:00      2
10:30:00     0
11:30:00     2
12:30:00     0
dtype: int64

In [ ]:
#we can also get the number of missing values in each row.
df.isna().sum(axis=1)

0     1
1     1
2     4
3     4
4     3
5     3
6     1
7     1
8     1
9     1
10    2
11    2
12    1
13    1
14    0
15    0
16    0
17    0
dtype: int64

- How to deal with null values?
    - delete the rows/columns containing the null values.
    - fill the missing values with some data/estimate.

In [ ]:
#drop the rows containing null values.
df.dropna() #rows with even a single missing value have been deleted.

Date               Drug_Name    Parameter  1:30:00  2:30:00  \
14  17-10-2020     docetaxel injection  Temperature     12.0     13.0   
15  17-10-2020     docetaxel injection     Pressure     20.0     22.0   
16  17-10-2020  ketamine hydrochloride  Temperature     13.0     14.0   
17  17-10-2020  ketamine hydrochloride     Pressure      8.0      9.0   

    3:30:00  4:30:00  5:30:00  6:30:00  7:30:00  8:30:00  9:30:00  10:30:00  \
14     14.0     15.0     16.0       17     18.0     19.0     20.0        21   
15     22.0     22.0     22.0       23     25.0     26.0     27.0        28   
16     15.0     16.0     17.0       18     19.0     20.0     21.0        22   
17     10.0     11.0     11.0       12     12.0     11.0     12.0        13   

    11:30:00  12:30:00  
14      22.0        23  
15      29.0        28  
16      23.0        24  
17      14.0        15

In [ ]:
#drop the columns having missing values
df.dropna(axis=1)

Date                Drug_Name    Parameter  6:30:00  10:30:00  \
0   15-10-2020  diltiazem hydrochloride  Temperature       22        20   
1   15-10-2020  diltiazem hydrochloride     Pressure       14        18   
2   15-10-2020      docetaxel injection  Temperature       18        23   
3   15-10-2020      docetaxel injection     Pressure       23        26   
4   15-10-2020   ketamine hydrochloride  Temperature       26        22   
5   15-10-2020   ketamine hydrochloride     Pressure        9         9   
6   16-10-2020  diltiazem hydrochloride  Temperature       38        40   
7   16-10-2020  diltiazem hydrochloride     Pressure       23        24   
8   16-10-2020      docetaxel injection  Temperature       49        56   
9   16-10-2020      docetaxel injection     Pressure       27        28   
10  16-10-2020   ketamine hydrochloride  Temperature       12        13   
11  16-10-2020   ketamine hydrochloride     Pressure       15        16   
12  17-10-2020  diltiazem hydrochloride  Temperature       16        14   
13  17-10-2020  diltiazem hydrochloride     Pressure        8        11   
14  17-10-2020      docetaxel injection  Temperature       17        21   
15  17-10-2020      docetaxel injection     Pressure       23        28   
16  17-10-2020   ketamine hydrochloride  Temperature       18        22   
17  17-10-2020   ketamine hydrochloride     Pressure       12        13   

    12:30:00  
0         21  
1         20  
2         25  
3         28  
4         20  
5         11  
6         42  
7         27  
8         58  
9         30  
10        15  
11        18  
12        10  
13        14  
14        23  
15        28  
16        24  
17        15

- Instead of dropping, it would be better to fill the missing value with some data.

In [ ]:
#How we can fill the missing values with some data?
df.fillna(0)

Date                Drug_Name    Parameter  1:30:00  2:30:00  \
0   15-10-2020  diltiazem hydrochloride  Temperature     23.0     22.0   
1   15-10-2020  diltiazem hydrochloride     Pressure     12.0     13.0   
2   15-10-2020      docetaxel injection  Temperature      0.0     17.0   
3   15-10-2020      docetaxel injection     Pressure      0.0     22.0   
4   15-10-2020   ketamine hydrochloride  Temperature     24.0      0.0   
5   15-10-2020   ketamine hydrochloride     Pressure      8.0      0.0   
6   16-10-2020  diltiazem hydrochloride  Temperature     34.0     35.0   
7   16-10-2020  diltiazem hydrochloride     Pressure     18.0     19.0   
8   16-10-2020      docetaxel injection  Temperature     46.0     47.0   
9   16-10-2020      docetaxel injection     Pressure     23.0     24.0   
10  16-10-2020   ketamine hydrochloride  Temperature      8.0      9.0   
11  16-10-2020   ketamine hydrochloride     Pressure     12.0     12.0   
12  17-10-2020  diltiazem hydrochloride  Temperature     20.0     19.0   
13  17-10-2020  diltiazem hydrochloride     Pressure      3.0      4.0   
14  17-10-2020      docetaxel injection  Temperature     12.0     13.0   
15  17-10-2020      docetaxel injection     Pressure     20.0     22.0   
16  17-10-2020   ketamine hydrochloride  Temperature     13.0     14.0   
17  17-10-2020   ketamine hydrochloride     Pressure      8.0      9.0   

    3:30:00  4:30:00  5:30:00  6:30:00  7:30:00  8:30:00  9:30:00  10:30:00  \
0       0.0     21.0     21.0       22     23.0     21.0     22.0        20   
1       0.0     11.0     13.0       14     16.0     16.0     24.0        18   
2      18.0      0.0     17.0       18      0.0      0.0     23.0        23   
3      22.0      0.0     22.0       23      0.0      0.0     27.0        26   
4       0.0     27.0      0.0       26     25.0     24.0     23.0        22   
5       0.0      7.0      0.0        9     10.0     11.0     10.0         9   
6      36.0     36.0     37.0       38     37.0     38.0     39.0        40   
7      20.0     21.0     22.0       23     24.0     25.0     25.0        24   
8       0.0     48.0     48.0       49     50.0     52.0     55.0        56   
9       0.0     25.0     26.0       27     28.0     29.0     28.0        28   
10     10.0      0.0     11.0       12     12.0     11.0      0.0        13   
11     13.0      0.0     15.0       15     15.0     15.0      0.0        16   
12     19.0     18.0     17.0       16     15.0      0.0     13.0        14   
13      4.0      4.0      6.0        8      9.0      0.0      9.0        11   
14     14.0     15.0     16.0       17     18.0     19.0     20.0        21   
15     22.0     22.0     22.0       23     25.0     26.0     27.0        28   
16     15.0     16.0     17.0       18     19.0     20.0     21.0        22   
17     10.0     11.0     11.0       12     12.0     11.0     12.0        13   

    11:30:00  12:30:00  
0       20.0        21  
1       19.0        20  
2       25.0        25  
3       29.0        28  
4       21.0        20  
5        9.0        11  
6        0.0        42  
7        0.0        27  
8       57.0        58  
9       29.0        30  
10      14.0        15  
11      17.0        18  
12      11.0        10  
13      13.0        14  
14      22.0        23  
15      29.0        28  
16      23.0        24  
17      14.0        15

- df.fillna(0) = it fills all missing values with 0.

In [ ]:
#let's fill it to a particular column
df['2:30:00'].fillna(1)

0     22.0
1     13.0
2     17.0
3     22.0
4      1.0
5      1.0
6     35.0
7     19.0
8     47.0
9     24.0
10     9.0
11    12.0
12    19.0
13     4.0
14    13.0
15    22.0
16    14.0
17     9.0
Name: 2:30:00, dtype: float64

In [ ]:
#We can use some kind of estimator 
#like mean, median etc 
df['2:30:00'].fillna(df['2:30:00'].mean())

0     22.0000
1     13.0000
2     17.0000
3     22.0000
4     18.8125
5     18.8125
6     35.0000
7     19.0000
8     47.0000
9     24.0000
10     9.0000
11    12.0000
12    19.0000
13     4.0000
14    13.0000
15    22.0000
16    14.0000
17     9.0000
Name: 2:30:00, dtype: float64

In [224]:
df_1 = data_tidy.copy()
df_1

None        Date      Time                Drug_Name  Pressure  Temperature
0     15-10-2020  10:30:00  diltiazem hydrochloride      18.0         20.0
1     15-10-2020  10:30:00      docetaxel injection      26.0         23.0
2     15-10-2020  10:30:00   ketamine hydrochloride       9.0         22.0
3     15-10-2020  11:30:00  diltiazem hydrochloride      19.0         20.0
4     15-10-2020  11:30:00      docetaxel injection      29.0         25.0
..           ...       ...                      ...       ...          ...
103   17-10-2020   8:30:00      docetaxel injection      26.0         19.0
104   17-10-2020   8:30:00   ketamine hydrochloride      11.0         20.0
105   17-10-2020   9:30:00  diltiazem hydrochloride       9.0         13.0
106   17-10-2020   9:30:00      docetaxel injection      27.0         20.0
107   17-10-2020   9:30:00   ketamine hydrochloride      12.0         21.0

[108 rows x 5 columns]

In [225]:
def temp_mean(x):
    x['Temp_Avg'] = x['Temperature'].mean()
    return x
df_1 = df_1.groupby(['Drug_Name'],group_keys=False).apply(temp_mean)
df_1

C:\Users\207498\AppData\Local\Temp\ipykernel_11920\470124318.py:4: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df_1 = df_1.groupby(['Drug_Name'],group_keys=False).apply(temp_mean)


None        Date      Time                Drug_Name  Pressure  Temperature  \
0     15-10-2020  10:30:00  diltiazem hydrochloride      18.0         20.0   
1     15-10-2020  10:30:00      docetaxel injection      26.0         23.0   
2     15-10-2020  10:30:00   ketamine hydrochloride       9.0         22.0   
3     15-10-2020  11:30:00  diltiazem hydrochloride      19.0         20.0   
4     15-10-2020  11:30:00      docetaxel injection      29.0         25.0   
..           ...       ...                      ...       ...          ...   
103   17-10-2020   8:30:00      docetaxel injection      26.0         19.0   
104   17-10-2020   8:30:00   ketamine hydrochloride      11.0         20.0   
105   17-10-2020   9:30:00  diltiazem hydrochloride       9.0         13.0   
106   17-10-2020   9:30:00      docetaxel injection      27.0         20.0   
107   17-10-2020   9:30:00   ketamine hydrochloride      12.0         21.0   

None   Temp_Avg  
0     24.848485  
1     30.387097  
2     17.709677  
3     24.848485  
4     30.387097  
..          ...  
103   30.387097  
104   17.709677  
105   24.848485  
106   30.387097  
107   17.709677  

[108 rows x 6 columns]

In [226]:
df_1['Temperature'].fillna(df_1['Temp_Avg'],inplace=True)

C:\Users\207498\AppData\Local\Temp\ipykernel_11920\3717634954.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_1['Temperature'].fillna(df_1['Temp_Avg'],inplace=True)


In [227]:
df_1

None        Date      Time                Drug_Name  Pressure  Temperature  \
0     15-10-2020  10:30:00  diltiazem hydrochloride      18.0         20.0   
1     15-10-2020  10:30:00      docetaxel injection      26.0         23.0   
2     15-10-2020  10:30:00   ketamine hydrochloride       9.0         22.0   
3     15-10-2020  11:30:00  diltiazem hydrochloride      19.0         20.0   
4     15-10-2020  11:30:00      docetaxel injection      29.0         25.0   
..           ...       ...                      ...       ...          ...   
103   17-10-2020   8:30:00      docetaxel injection      26.0         19.0   
104   17-10-2020   8:30:00   ketamine hydrochloride      11.0         20.0   
105   17-10-2020   9:30:00  diltiazem hydrochloride       9.0         13.0   
106   17-10-2020   9:30:00      docetaxel injection      27.0         20.0   
107   17-10-2020   9:30:00   ketamine hydrochloride      12.0         21.0   

None   Temp_Avg  
0     24.848485  
1     30.387097  
2     17.709677  
3     24.848485  
4     30.387097  
..          ...  
103   30.387097  
104   17.709677  
105   24.848485  
106   30.387097  
107   17.709677  

[108 rows x 6 columns]

<b>Pandas Cut</b>

In [228]:
temp_points = [5,20,35,50,60]
temp_labels = ['low','medium','high','very_high']
df_1['Temp_Cat'] = pd.cut(df_1['Temperature'],
                          bins=temp_points,
                          labels=temp_labels)
df_1

None        Date      Time                Drug_Name  Pressure  Temperature  \
0     15-10-2020  10:30:00  diltiazem hydrochloride      18.0         20.0   
1     15-10-2020  10:30:00      docetaxel injection      26.0         23.0   
2     15-10-2020  10:30:00   ketamine hydrochloride       9.0         22.0   
3     15-10-2020  11:30:00  diltiazem hydrochloride      19.0         20.0   
4     15-10-2020  11:30:00      docetaxel injection      29.0         25.0   
..           ...       ...                      ...       ...          ...   
103   17-10-2020   8:30:00      docetaxel injection      26.0         19.0   
104   17-10-2020   8:30:00   ketamine hydrochloride      11.0         20.0   
105   17-10-2020   9:30:00  diltiazem hydrochloride       9.0         13.0   
106   17-10-2020   9:30:00      docetaxel injection      27.0         20.0   
107   17-10-2020   9:30:00   ketamine hydrochloride      12.0         21.0   

None   Temp_Avg Temp_Cat  
0     24.848485      low  
1     30.387097   medium  
2     17.709677   medium  
3     24.848485      low  
4     30.387097   medium  
..          ...      ...  
103   30.387097      low  
104   17.709677      low  
105   24.848485      low  
106   30.387097      low  
107   17.709677   medium  

[108 rows x 7 columns]

- We can use it to convert continuous data to cat. data
    - We need to provide:
        - continuous data
        - bins edges(array of numbers) to 'cut' the entire range
        - labels corresponding to every bin

In [230]:
df_1['Temp_Cat'].value_counts()

Temp_Cat
low          50
medium       38
high         15
very_high     5
Name: count, dtype: int64

In [231]:
#How can you filter rows containing hydrocholric in their drug name?
df_1.loc[df_1['Drug_Name'].str.contains('hydrochloride')].head()

None        Date      Time                Drug_Name  Pressure  Temperature  \
0     15-10-2020  10:30:00  diltiazem hydrochloride      18.0         20.0   
2     15-10-2020  10:30:00   ketamine hydrochloride       9.0         22.0   
3     15-10-2020  11:30:00  diltiazem hydrochloride      19.0         20.0   
5     15-10-2020  11:30:00   ketamine hydrochloride       9.0         21.0   
6     15-10-2020  12:30:00  diltiazem hydrochloride      20.0         21.0   

None   Temp_Avg Temp_Cat  
0     24.848485      low  
2     17.709677   medium  
3     24.848485      low  
5     17.709677   medium  
6     24.848485   medium

- Series.str.function()
- Series.str can be used to access the values of the series as strings and apply several methods to it.

In [232]:
df_1['Date'].str.split('-')

0      [15, 10, 2020]
1      [15, 10, 2020]
2      [15, 10, 2020]
3      [15, 10, 2020]
4      [15, 10, 2020]
            ...      
103    [17, 10, 2020]
104    [17, 10, 2020]
105    [17, 10, 2020]
106    [17, 10, 2020]
107    [17, 10, 2020]
Name: Date, Length: 108, dtype: object

In [233]:
df_1['Date'].str.split('-').apply(lambda x : x[2])

0      2020
1      2020
2      2020
3      2020
4      2020
       ... 
103    2020
104    2020
105    2020
106    2020
107    2020
Name: Date, Length: 108, dtype: object

<b>Datetime</b>

In [234]:
df_1['Timestamp'] = df_1['Date']+" "+df_1['Time']
df_1

None        Date      Time                Drug_Name  Pressure  Temperature  \
0     15-10-2020  10:30:00  diltiazem hydrochloride      18.0         20.0   
1     15-10-2020  10:30:00      docetaxel injection      26.0         23.0   
2     15-10-2020  10:30:00   ketamine hydrochloride       9.0         22.0   
3     15-10-2020  11:30:00  diltiazem hydrochloride      19.0         20.0   
4     15-10-2020  11:30:00      docetaxel injection      29.0         25.0   
..           ...       ...                      ...       ...          ...   
103   17-10-2020   8:30:00      docetaxel injection      26.0         19.0   
104   17-10-2020   8:30:00   ketamine hydrochloride      11.0         20.0   
105   17-10-2020   9:30:00  diltiazem hydrochloride       9.0         13.0   
106   17-10-2020   9:30:00      docetaxel injection      27.0         20.0   
107   17-10-2020   9:30:00   ketamine hydrochloride      12.0         21.0   

None   Temp_Avg Temp_Cat            Timestamp  
0     24.848485      low  15-10-2020 10:30:00  
1     30.387097   medium  15-10-2020 10:30:00  
2     17.709677   medium  15-10-2020 10:30:00  
3     24.848485      low  15-10-2020 11:30:00  
4     30.387097   medium  15-10-2020 11:30:00  
..          ...      ...                  ...  
103   30.387097      low   17-10-2020 8:30:00  
104   17.709677      low   17-10-2020 8:30:00  
105   24.848485      low   17-10-2020 9:30:00  
106   30.387097      low   17-10-2020 9:30:00  
107   17.709677   medium   17-10-2020 9:30:00  

[108 rows x 8 columns]

In [235]:
#let's convert our timestamp column
df_1['Timestamp'] = pd.to_datetime(df_1['Timestamp'])

C:\Users\207498\AppData\Local\Temp\ipykernel_11920\2954105617.py:2: UserWarning: Parsing dates in %d-%m-%Y %H:%M:%S format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df_1['Timestamp'] = pd.to_datetime(df_1['Timestamp'])


In [237]:
df_1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 108 entries, 0 to 107
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype         
---  ------       --------------  -----         
 0   Date         108 non-null    object        
 1   Time         108 non-null    object        
 2   Drug_Name    108 non-null    object        
 3   Pressure     95 non-null     float64       
 4   Temperature  108 non-null    float64       
 5   Temp_Avg     108 non-null    float64       
 6   Temp_Cat     108 non-null    category      
 7   Timestamp    108 non-null    datetime64[ns]
dtypes: category(1), datetime64[ns](1), float64(3), object(3)
memory usage: 11.1+ KB


In [239]:
ts = df_1['Timestamp'][0]
ts

Timestamp('2020-10-15 10:30:00')

In [240]:
#how to extract year
ts.year

2020

In [241]:
#month
ts.month

10

In [242]:
#day
ts.day

15

In [243]:
#month name
ts.month_name()

'October'

In [244]:
#day_name of the week on that date
ts.day_name()

'Thursday'

In [245]:
#day of week
ts.day_of_week

3

In [246]:
ts.hour

10

In [248]:
ts.minute

30

- We can use this data from the columns as a whole using .dt object
- dt gives properties of values in a column
- from this DatetimeProperties of column 'end', we extract year

In [249]:
df_1['Timestamp'].dt.year

0      2020
1      2020
2      2020
3      2020
4      2020
       ... 
103    2020
104    2020
105    2020
106    2020
107    2020
Name: Timestamp, Length: 108, dtype: int32

strftime - stringformat time, to modify our datetime format

In [251]:
df_1['Timestamp'][0].strftime('%Y')

str

In [254]:
df_1['Timestamp'][0].strftime('%m'), df_1['Timestamp'][0].strftime('%d')

('10', '15', '00')

In [ ]:
df_1['Timestamp'][0].strftime('%S') #Seconds

- Similarly, we can combine the format types to modify the date-time format as per our convinience

In [255]:
df_1['Timestamp'][0].strftime('%m-%d')

'10-15'

In [ ]:
#Writing to files
df_1.to_csv('medicine_tidy.csv',sep=',') #we have to provide the path and file name in which you wan to store th data.